### ISSUE TITLE
unknown field "Cache_Use_Docker_Id"

### ISSUE THREAD

**Issue by dtwork2022** [banzaicloud/logging-operator#1002]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
Cache_Use_Docker_Id is not included in the Fluentbit specs for io.banzaicloud.logging.v1beta1.Logging.spec.fluentbit.filterKubernetes but has been a part of upstream Fluentbit since v1.7.0 [Code Entry](https://github.com/fluent/fluent-bit/blob/v1.7.0/plugins/filter_kubernetes/kube_conf.h#L77). Latest release is using Fluentbit image v1.8.

**Expected behaviour**:
Should accept value and populate the Fluentbit FilterKubernetes config.

**Steps to reproduce the bug**:
Provide a values file with the following to the latest v3.17.5 helm chart
```
fluentbit:
  filterKubernetes:
    Cache_Use_Docker_Id: true
```

**Environment details**:
- Kubernetes version (e.g. v1.15.2):  v1.18.20
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): On-premise
- logging-operator version (e.g. 2.1.1): v3.17.5
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
```
Helm upgrade failed: error validating "": error validating data: ValidationError(Logging.spec.fluentbit.filterKubernetes): unknown field "Cache_Use_Docker_Id" in io.banzaicloud.logging.v1beta1.Logging.spec.fluentbit.filterKubernetes```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by ahma** [comment]
@dtwork2022 Thanks for the report.

**Comment by dtwork2022** [comment]
@ahma Thanks for the quick reply! Any idea the turnaround for this to make it into a release ?

**Comment by ahma** [comment]
@dtwork2022 Maybe the next week.
