### ISSUE TITLE
Cluster name is hardcoded as cluster.local

### ISSUE THREAD

**Issue by ecusnir** [banzaicloud/logging-operator#1021]
**Describe the bug**:
Since PR [#894](https://github.com/banzaicloud/logging-operator/pull/894) the cluster name has been hardcoded as `cluster.local`, causing problems if this is not the actual name. 

**Expected behaviour**:
Cluster name should be configurable and not hardcoded.

**Comment by aslafy-z** [comment]
What do you think of removing the cluster domain name altogether and letting the dns provider take care of routing the the right place instead of allowing it to be customized? 

@ecusnir @ahma @siliconbrain

**Comment by siliconbrain** [comment]
@aslafy-z I'm not sure this is feasible in all cases, like with a service mesh or other multi-cluster setup. I agree with @ecusnir, the cluster name should be configurable.

**Comment by ecusnir** [comment]
I believe this is how it used to be and it worked well in my case. However, I agree with @siliconbrain that it should be configurable since the code has changed and I don’t see a reason to go back to the old version.
