### ISSUE TITLE
Add logging-operator to OperatorHub.io

### ISSUE THREAD

**Issue by dmesser** [banzaicloud/logging-operator#109]
It would be nice if `logging-operator` could be packaged and used with [Operator Lifecycle Manager](https://github.com/operator-framework/operator-lifecycle-manager). As a side effect you could also promote your Operator, like other BanzaiCloud Operators already, on https://operatorhub.io 

Instructions about packaging can be found here https://operatorhub.io/contribute and in more detail here https://github.com/operator-framework/community-operators/blob/master/docs/testing-operators.md#manual-testing-on-kubernetes

**Comment by tarokkk** [comment]
Maintaining an operator at the operatorhub.io requires a lot of energy and human intervention, considering our CRDs that extend features with every plugin supported is just too much effort. If there is a way to automatize the process we can open a new issue.

**Comment by dmesser** [comment]
Operatorhub.io automated the entire testing since last year. An update is now as simple as creating a new directory with all your new CRDs and the metadata file (CSV).
