### ISSUE TITLE
How to set this setting for fluentd plugin: log_es_400_reason

### ISSUE THREAD

**Issue by imriss** [banzaicloud/logging-operator#112]
**Is your feature request related to a problem? Please describe.**
To debug `error="400 - Rejected by Elasticsearch"` errors, I need to set `log_es_400_reason` to `true`.

**Describe the solution you'd like**
An option to set `log_es_400_reason` via `values.yaml`

**Describe alternatives you've considered**
N/A

**Additional context**
```
2019-07-26 17:38:07 +0000 [warn]: #0 dump an error event: error_class=Fluent::Plugin::ElasticsearchErrorHandler::ElasticsearchError error="400 - Rejected by Elasticsearch" 
```

**Comment by imriss** [comment]
@pepov many thanks. My mistake, I thought that the `Logging Operator` is using [uken/fluent-plugin-elasticsearch](https://github.com/uken/fluent-plugin-elasticsearch) for the plugin. I just noticed that it is using the plugins that come with the `Fluent Bit`. The flag for tracing seems to be `Trace_Output` in that plugin: https://docs.fluentbit.io/manual/v/1.1/output/elasticsearch

Please let me know. Thanks

**Comment by imriss** [comment]
or probably is this one? 
https://www.rubydoc.info/gems/fluent-plugin-elasticsearch/1.5.0

**Comment by pepov** [comment]
Sorry for the late response. It is using `https://github.com/uken/fluent-plugin-elasticsearch` with version `3.5.2`:

You can check it like this:
```
docker run --rm -ti banzaicloud/fluentd:v1.5.0 bash -c " gem list fluent-plugin-elasticsearch -d"

*** LOCAL GEMS ***

fluent-plugin-elasticsearch (3.5.2)
    Authors: diogo, pitr
    Homepage: https://github.com/uken/fluent-plugin-elasticsearch
    License: Apache-2.0
    Installed at: /usr/local/bundle

    Elasticsearch output plugin for Fluent event collector
```

**Comment by imriss** [comment]
Thanks

**Comment by tirelibirefe** [comment]
How can we pass "log_es_400_reason true" in Fluentd values file?
