### ISSUE TITLE
Please add `reload_on_failure true` and `reload_connections false` to elasticsearch plugin

### ISSUE THREAD

**Issue by imriss** [banzaicloud/logging-operator#117]
**Is your feature request related to a problem? Please describe.**
I am facing the `read timeout reached` error:
```
2019-07-31 13:18:45 +0000 [warn]: #0 failed to flush the buffer. retry_time=39 next_retry_seconds=2019-07-31 13:19:17 +0000 chunk="58ef9d0d26d38d31e2579a76d7b3ad21" error_class=Fluent::Plugin::ElasticsearchOutput::RecoverableRequestFailure error="could not push logs to Elasticsearch cluster ({:host=>\"elasticsearch-elasticsearch-cluster.default\", :port=>9200, :scheme=>\"https\"}): read timeout reached"
```

In [here ](https://github.com/uken/fluent-plugin-elasticsearch/issues/525#issuecomment-475502715) and [here](https://github.com/uken/fluent-plugin-elasticsearch#stopped-to-send-events-on-k8s-why), it is suggested to add the following to the output config to resolve the issue:
```
reconnect_on_error true
reload_on_failure true
reload_connections false
```

The `reconnect_on_error true` is already there, but `reload_on_failure` and `reload_connections` are missing.

**Describe the solution you'd like**
Please add `reload_on_failure true` and `reload_connections false` to the elasticsearch plugin

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pepov** [comment]
Hi, my bad, I should have added all the plugin parameters in the previous release. Will add all options soon.

**Comment by imriss** [comment]
Hi, thanks. After redeploying everything, the error disappeared for now.

**Comment by pepov** [comment]
Glad to hear, then I don't have to hurry with adding the missing params. Will add those with the following release though, just not sure when it will happen.

**Comment by tarokkk** [comment]
Logging-operator v2 is out and all the attributes are accessible for [Elasticsearch](https://github.com/banzaicloud/logging-operator/blob/v2/docs/plugins/outputs/elasticsearch.md)
