### ISSUE TITLE
Default bufferPath settings are unique and prevent reuse

### ISSUE THREAD

**Issue by ncrothe** [banzaicloud/logging-operator#119]
**Describe the bug**
When setting up two different pieces of fluentd config via Plugin definitions, both configuring a Forward output, the Fluentd container started crashing with the error
`config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="Other 'forward' plugin already use same buffer path: type = forward, buffer path = /buffers/forward"`

**To Reproduce**
1. Create a CR that defines a forward output, do not set bufferPath parameter
2. Create another CR that also defines a forward output (but don't set bufferPath)
3. Fluentd will go into a CrashLoop

**Expected behavior**
Fluentd does not crash and forwards log events to both forward locations.

**Additional context**
The error seems to be due to a non-unique default value for bufferPath. This seems to affect other output plugins as well. A potential solution might append some unique string to the default path. K8s resource name could be an option of the name value set during output configuration (like in https://github.com/banzaicloud/logging-operator/blob/master/charts/nginx-logging-demo/templates/logging.yaml#L17).

**Comment by tarokkk** [comment]
In the v2 this is a required value. We will come-op some clever default but now it depends on the user
