### ISSUE TITLE
enable logging operator chart to configure fluentd-config config map

### ISSUE THREAD

**Issue by nparfait** [banzaicloud/logging-operator#120]
I would like to be able to customise the fluentd instance installed by logging operator.
Eg. I would like to add some tags as following
```
    <filter *.**>
      @type record_transformer
      <record>
        cluster "mgmt.cluster"
        tag ${tag}
      </record>
    </filter>
```

I would like to be able to specify custom values in the fluentd-config config map (above filter).

**Comment by nparfait** [comment]
I saw this - https://github.com/banzaicloud/logging-operator/pull/116/commits/2329044ea781e239795418c3c24b9acde6455aa9

I've forked and create a custom filter plugin. As well as a custom banzai fluentd image with ec-metadata plugin. Which seems to do what i want.

**Comment by tarokkk** [comment]
As the logging-operator v2 is out I would recommend to submit an issue or a PR with the required filter plugins. It is much easier now to create specified filters in the logging-operator: https://github.com/banzaicloud/logging-operator/blob/v2/docs/developers.md
