### ISSUE TITLE
Improve tagging / categorisation

### ISSUE THREAD

**Issue by estahn** [banzaicloud/logging-operator#125]
**Is your feature request related to a problem? Please describe.**

We're migrating from the Sumologic native helm chart to logging operator. The native helm chart has great categorisation and we would like to keep this intact. It allows for easy filtering and other things. The main difference I can see is that the logging-operator does not go from "biggest to smallest" but "smallest to biggest" in terms of tagging (e.g. `ingress-nginx.kube-ingress.kubernetes` vs `kubernetes.kube-ingress.ingress-nginx`).

```
Name: kube-ingress.ingress-nginx-6fb488866-s85z9.nginx-ingress-controller
Category: kubernetes/kube/ingress/ingress/nginx/6fb488866
```

```
config_param :source_category, :string, :default => "%{namespace}/%{pod_name}"
config_param :source_name, :string, :default => "%{namespace}.%{pod}.%{container}"
```

**Describe the solution you'd like**
More granular tagging.

**Comment by pepov** [comment]
I think we can put together something more flexible in terms of allowing a set of variables that can be referenced from the parsed kubernetes metadata similar to what you described.

**Comment by pepov** [comment]
@estahn we are working on a new version of the operator that will leverage the following plugin to rewrite tags based on log records: https://github.com/banzaicloud/fluent-plugin-tag-normaliser

We are not planning to implement this for the current version, so please stay tuned to see it coming in v2 in a more flexible way.

**Comment by tarokkk** [comment]
Logging-operator v2 is out and [tag-normaliser](https://github.com/banzaicloud/logging-operator/blob/v2/docs/plugins/filters/tagnormaliser.md) is available.
