### ISSUE TITLE
Extend CRD to support serviceAnnotations

### ISSUE THREAD

**Issue by ekarlso** [banzaicloud/logging-operator#126]
**Is your feature request related to a problem? Please describe.**
Yes, create internal lb's instead of public lb when having this create a serviceType of LoadBalancer

**Describe the solution you'd like**
I would like to pass annotations to be used on the service and not just be able to set serviceType.reasoning behind this is that Azure uses mechanisms like this to create internal lb's vs external ones.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tarokkk** [comment]
Operator manages internal services only at the moment. We will consider custom annotations, labels etc when we are working on publicly accessible service endpoints. Thanks for the note on this.
