### ISSUE TITLE
Add fluent-plugin-splunk-enterprise support

### ISSUE THREAD

**Issue by tarokkk** [banzaicloud/logging-operator#158]
More information at: https://github.com/fluent/fluent-plugin-splunk

**Comment by danmx** [comment]
There is an official integration https://github.com/splunk/fluent-plugin-splunk-hec

**Comment by stefanhenseler** [comment]
Is anyone actively working on this? I would be available to help to implement support for Splunk Enterprise, I currently have a use case.

**Comment by pepov** [comment]
not at the moment
