### ISSUE TITLE
Expose resource settings for in v1 helm chart

### ISSUE THREAD

**Issue by ncrothe** [banzaicloud/logging-operator#167]
**Describe the bug**
The helm chart for v1 logging-operator-fluent hard-codes empty resource settings. This should be exposed as configurable. See: https://github.com/banzaicloud/logging-operator/blob/v1/charts/logging-operator-fluent/templates/fluentd-cr.yaml#L21

**Steps to reproduce the issue:**
See helm chart.

**Expected behavior**
The helm chart checks for fluentd,resources or some similar variable before expression resource settings.

**Additional context**
This is about v1 of the logger.

**Comment by ahma** [comment]
Updated chart (logging-operator-fluent) version 1.0.1
