### ISSUE TITLE
fluentbit unable to connect to apiserver

### ISSUE THREAD

**Issue by Thoro** [banzaicloud/logging-operator#172]
**Describe the bug**

Fluentbit constantly logs the following error:

```
[2019/10/04 22:26:39] [error] [filter_kube] upstream connection error
[2019/10/04 22:26:39] [error] [io_tls] flb_io_tls.c:348 X509 - Certificate verification failed, e.g. CRL, CA or signature check
```

But the certificate is correct:

```
curl https://kubernetes.default.svc:443 --cacert /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```

Returns no certificate error, and the certificate definitely has the correct Alternative Names:

X509v3 Subject Alternative Name:
                IP Address:10.253.252.1, IP Address:10.21.13.5, IP Address:10.21.13.15, IP Address:10.21.13.25, DNS:kubernetes, DNS:kubernetes.default, DNS:kubernetes.default.svc, DNS:kubernetes.default.svc.cluster.local, DNS:at-host-02, DNS:at-host-12, DNS:at-host-22

**Steps to reproduce the issue:**

Start default configuration.

**Expected behavior**

Connection to apiserver will work, or there is an option to change the apiserver url / set the ssl.verify option in the config file.

See for similar issues: https://github.com/fluent/fluent-bit/issues/367
See for the options:  https://docs.fluentbit.io/manual/filter/kubernetes

**Screenshots**

**Additional context**

**Comment by tarokkk** [comment]
I'll close this issue prior to: https://github.com/fluent/fluent-bit/issues/1615
