### ISSUE TITLE
Fluentbit configuration does not reload

### ISSUE THREAD

**Issue by Thoro** [banzaicloud/logging-operator#173]
**Describe the bug**

If you update the fluentbit config part, it's not reloaded in fluentbit
(I believe it can't even do this)

**Steps to reproduce the issue:**

Update the fluentbit config.

**Expected behavior**

Reload the config without rereading all log files

**Screenshots**

**Additional context**

**Comment by tarokkk** [comment]
Fluent-bit configuration is not (yet) intended to reload, it only works as a collector. The configurations are generated and only disruptive (re-create pods) updates possible (https://github.com/fluent/fluent-bit-docs/issues/210). Do you have specific use-case for this?

**Comment by Thoro** [comment]
The use case would be testing and setting up the log collector.

I don't believe that during normal operation it should need to do this, but it's very confusing that all parts are updated by the operator, but the fluentbit part is not restarted.
