### ISSUE TITLE
Fluentbit always read all log files from the beginning

### ISSUE THREAD

**Issue by Thoro** [banzaicloud/logging-operator#174]
**Describe the bug**

Whenever fluentbit is restarted (reloaded config) it rereads all logs files form the beginning

**Steps to reproduce the issue:**

Delete the deaemonset for fluentbit

**Expected behavior**

continue reading where it left off

Either have a hostPath or a pvc to save the DB from the fluentbit Input Plugin

**Screenshots**

**Additional context**

**Comment by tarokkk** [comment]
We will add options to enable hostPath, PVC for fluent-bit and set position file accordingly thanks for reporting it.
