### ISSUE TITLE
Allow to configure the "MountPath" for  Fluent-bit "DaemonSet" 

### ISSUE THREAD

**Issue by MChorfa** [banzaicloud/logging-operator#197]
Not all dockers are installed on the same path. However, the following implementation is hardcoded:  
- https://github.com/banzaicloud/logging-operator/blob/3592cb99f568090cc0aa3955ad5d34cba0af2c76/pkg/resources/fluentbit/daemonset.go#L80 
- https://github.com/banzaicloud/logging-operator/blob/3592cb99f568090cc0aa3955ad5d34cba0af2c76/pkg/resources/fluentbit/daemonset.go#L115
Is there a way to pass "MounthPath" by config?

thank you

**Comment by pepov** [comment]
hi @MChorfa currently there is no way to pass in custom config. We can make it configurable in a future release but feel free to send a pull request as well, thanks for the report!
