### ISSUE TITLE
Add Detect Exceptions plugin to fluent-d image

### ISSUE THREAD

**Issue by eNettMattD** [banzaicloud/logging-operator#236]
**Is your feature request related to a problem? Please describe.**
By default, fluentd (and other log forwarders) don't handle multi-line logs well. This is particularly evident with stack traces in a managed language like java or c#. There are several ways around this with fluentd, and the best way, is via the detect exceptions plugin - https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions

**Describe the solution you'd like**
Include this plugin with the fluentd image provided by the operator

**Describe alternatives you've considered**
The alternative would involve me forking your helm charts and changing the fluentd image

**Additional context**
None

**Comment by ahma** [comment]
Done
