### ISSUE TITLE
Monitoring not working for fluentd

### ISSUE THREAD

**Issue by tesharp** [banzaicloud/logging-operator#240]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
Using latest master release it doesn't scrape prometheus metrics correctly from fluentd. (Using latest master since that works with PSP, 2.5.0 doesn't)

**Expected behaviour**:
Get prometheus metrics for fluentd

**Steps to reproduce the bug**:
Deploy master and check prometheus stats.

**Additional context**:
There is introduced a bug in https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/fluentd/config.go#L27 where it uses a default function that does not exist (assume you wanted the function available in sprig). This leads to `generateConfig` in https://github.com/banzaicloud/logging-operator/blob/master/pkg/resources/fluentd/configsecret.go getting an error and returning empty string. On another note please don't just ignore errors in `generateConfig`... it makes it hard to locate the problem, and bad practice.

/kind bug

**Comment by pepov** [comment]
@tesharp thanks for reporting!

to be clear, is the bug in the fluentd config causes the issue with monitoring, or is that a different one?

**Comment by tesharp** [comment]
The bug in fluentd config causes empty `input.conf` element in fluentd config secret, which leads to issue with monitoring since fluentd doesn't expose metrics as it should.

**Comment by pepov** [comment]
@tesharp I haven't tested this, but should fix it
