### ISSUE TITLE
Create a Helm 3 compatible chart for the logging-operator

### ISSUE THREAD

**Issue by RushedLogic** [banzaicloud/logging-operator#276]
Helm 3 has removed the crd-install hooks in favour of a crds directory: https://helm.sh/docs/topics/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you

The current CRDs for the logging-operator helm chart are located in the templates folder. When using helm 3 to install a helm chart with the logging-operator as a dependency the CRDs are not 
installed before they are needed.

Can we create a Helm 3 compatible chart for the logging operator.

**Comment by pepov** [comment]
Hi @RushedLogic!
Thanks for using the operator and creating the issue, however this change as you suggest would introduce a breaking change to existing helm v2 clients.

We will consider however to create a chart that specifically supports helm3 and deprecate the helm2 version on a longer term.

**Comment by RushedLogic** [comment]
Hey @pepov
Thanks for the reply! That seems like a much better course of action, I've updated the issue to match.

**Comment by eNettMattD** [comment]
Yes please, this is a significant blocker for us, as we have security requirements that prohibit the use of Tiller, so we are limited to using Helm 3.

**Comment by srmcleman** [comment]
Currently using the logging operator to send Falco logs to Sumo Logic (thanks btw, works fantastic) and would also really appreciate this!

**Comment by AakashMasand** [comment]
Hi, we are using Helm 3 as well because of the security issues associated with Tiller. This would be good to have.

**Comment by pepov** [comment]
Wow! Glad that the operator works great for you and that you are all looking to go forward with it. Of course we will add a helm3 compatible chart soon.

If you use the operator in production I would like to kindly ask you to add yourself to the list of adopters here:
https://github.com/banzaicloud/logging-operator/blob/master/ADOPTERS.md

**Comment by pepov** [comment]
We decided to simply add a flag `createCustomResource=true` that is compatible with helm v2 clients and you can use it with helm v3 by setting it to `false`.

**Comment by RushedLogic** [comment]
Thanks @pepov 
I can confirm that's working for me.
