### ISSUE TITLE
Must explicitly state ip_address for instance_profile_credentials even though it has a default value

### ISSUE THREAD

**Issue by nitinmohan87** [banzaicloud/logging-operator#277]
**Is your feature request related to a problem? Please describe.**
I am trying to setup the logging operator output CRD to use the instance profile credentials to store logs to S3. From the README, I see that the `instance_profile_credentials.ip_address` has a default value of `169.254.169.254`. I would expect the following the output config to use the instance_profile_credentials IP since I don't specify other credential types

```
$ kubectl -n logging apply -f - <<"EOF"
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: s3-output
  namespace: logging
spec:
  s3:
    s3_bucket: my-s3-bucket
    s3_region: us-east-1
    path: logs/${tag}/%Y/%m/%d/
    buffer:
      timekey: 10m
      timekey_wait: 30s
      timekey_use_utc: true
EOF
```
But I see this in the operator logs which seems to imply I must provide the IP address explicitly for it to work?

```
{"level":"error","ts":1575326763.5315049,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"logging","request":"/default-logging-simple","error":"failed to create model: failed to create configured output s3-output: One of AssumeRole
Credentials or SharedCredentials or InstanceProfileCredentials must be configured","errorVerbose":"One of AssumeRoleCredentials or SharedCredentials or InstanceProfileCredentials must be configured\nfailed to create configured output s3-output
...
```

**Describe the solution you'd like**
Possible have a seaparte config value like `instance_profile_credentials.enabled` and use that to determine whether to use instance_profile_credentials.

**Comment by pepov** [comment]
@nitinmohan87 you have to specify the field with at least an empty map if all the attributes are optional like this:
```
spec:
  s3:
    instance_profile_credentials: {}
```
let us know, whether that worked for you or not!

**Comment by nitinmohan87** [comment]
@pepov That worked. I should have thought of that before creating the issue. Thanks!

**Comment by pepov** [comment]
@nitinmohan87 no problem, glad I could help!
