### ISSUE TITLE
Enable configuring priorityClassName

### ISSUE THREAD

**Issue by mcculloughsco** [banzaicloud/logging-operator#291]
**Is your feature request related to a problem? Please describe.**
We are having problems where individual fluentbit pods aren't being scheduled on nodes that are already at capacity. We specify certain priority classes based on how critical a given service is to a node. We manually fix this by editing the fluentbit daemonset and setting the priority class, which allows the pods to then be scheduled. It would be great to be able to configure this on deployment.

**Describe the solution you'd like**
Allow configuring the priorityClassName for fluentbit, as well as fluentd. 

**Describe alternatives you've considered**
We are currently doing this manually once the daemonset is live.

**Comment by pepov** [comment]
@mcculloughsco I beleive this is already configurable with version 2.6.0 for fluentd and for fluentbit as well, although the documentation is misleading on it currently, but we will fix that.
