### ISSUE TITLE
Filter logs that are coming from certain namespaces on fluent-bit

### ISSUE THREAD

**Issue by dududko** [banzaicloud/logging-operator#292]
**Is your feature request related to a problem? Please describe.**
In some cases I need to have a separate logging system that is configured to process logs from a single namespace. At this moment it can be achieved with the use of a CRD Flow, which is namespace-specific. However in this solution all collected log events are filtered on a fluentd service, which will require a lot of additional CPU and Memory resources, depending on amount of logs stored on cluster nodes.

Here is how many resources a logging system require in my case
```
➜ kubectl -n logging-operator top pods
NAME                                 CPU(cores)   MEMORY(bytes)
logging-cloudwatch-fluentbit-444f2   44m          11Mi
logging-cloudwatch-fluentbit-5pmn7   1m           10Mi
logging-cloudwatch-fluentbit-bns4b   82m          15Mi
logging-cloudwatch-fluentbit-c2vc6   1m           12Mi
logging-cloudwatch-fluentbit-f8k5p   74m          14Mi
logging-cloudwatch-fluentbit-fqwm6   2m           11Mi
logging-cloudwatch-fluentbit-g9vwm   65m          10Mi
logging-cloudwatch-fluentbit-ms7r8   31m          12Mi
logging-cloudwatch-fluentbit-r8xx4   8m           9Mi
logging-cloudwatch-fluentd-0         374m         433Mi
logging-operator-8457774cc4-gsqld    5m           75Mi
```

The alternative solution is to filter logs on fluent-bit. A managed to do by adding the following section to the fluentbit config file between kubernetes and output blocks.
```
    [FILTER]
      Name         nest
      Match        *
      Operation    lift
      Nested_under kubernetes
      Prefix_with  k8s:

    [FILTER]
      Name         grep
      Match        *
      Regex        k8s:namespace_name ^({{ .Values.match_namespaces | join "|" }})$

    [FILTER]
      Name           nest
      Match          *
      Operation      nest
      Nest_under     kubernetes
      Remove_prefix  k8s:
      Wildcard       k8s:*
```

I am using **logging.customConfigSecret** to pass a custom config file to the fluent-bit daemonset.

This allows to consume significantly less resources in the logging system.

```
➜ kubectl -n logging-operator top pods
NAME                                 CPU(cores)   MEMORY(bytes)
logging-cloudwatch-fluentbit-2ln52   1m           5Mi
logging-cloudwatch-fluentbit-57bq6   1m           4Mi
logging-cloudwatch-fluentbit-97w8j   1m           5Mi
logging-cloudwatch-fluentbit-cdjzv   2m           5Mi
logging-cloudwatch-fluentbit-dx96l   8m           5Mi
logging-cloudwatch-fluentbit-jvlhv   2m           5Mi
logging-cloudwatch-fluentbit-ppj9k   13m          5Mi
logging-cloudwatch-fluentbit-vc2t5   2m           6Mi
logging-cloudwatch-fluentbit-wh9nc   2m           4Mi
logging-cloudwatch-fluentd-0         5m           92Mi
logging-operator-8457774cc4-gsqld    2m           75Mi
```

**Describe the solution you'd like**
I would like to have this configuration as a common case in the logging operator. I would like to be able to configure in the Logging CRD the list of namespaces from which fluent-bit has to collect logs and forward them to fluentd.  

You can add, say, `Logging.fluentbit.accept_namespaces` (keep logs from a given list of namespaces) and `Logging.fluentbit.ignore_namespaces` (filter logs from a given list of namespaces) to the config part of a CRD Logging.

**Describe alternatives you've considered**
Alternatively you can add `Logging.fluentbit.filter`, to be able to pass a custom filter config blocks to the config file. 

**Additional context**

**Comment by tarokkk** [comment]
Thank you for submitting your request!

Your use-case is really interesting however it sounds more like an edge case. I have some questions and notes regarding that.

1. Your measurement seems a bit strange to me. You moved a parsing logic to the edges and yet the fluent-bit resource consumption is lower than before. I would love to see some more specific instruction what kind of workload you have to transfer and how you are doing it.

2. If we move this kind of filtering to the edges it makes the behaviour of the operator **inconsistent**. If you create rules in a namespaces that filtered in fluent-bit you won't get any logs out of them.

3. Now fluent-bit is a thin layer of the Logging Operator ecosystem mainly for log collecting. It's not preferred to move a lot of logic there before live config reload is possible. Moreover you can move your fluentd workload to preferred nodes (as a statefulset it is obvious to use selectors, tolerations) but you can't move around / scale fluent-bit as it is required on all nodes.

4. The configuration you described is a workaround with 3 steps
lift -> grep -> nest
Implementing this as Stream processor rule or Lua filter seems much more efficient than moving around the metadata of the record.

tl&dr:
Now we cant support these kind of configurations but in the future we can come up with something generic / useful solution for these performance sensitive cases.

**Comment by dududko** [comment]
@tarokkk Thank you for your answer!

For a better understanding let me tell you a bit more about the use case I am workin with.

A kubernetes cluster contains some important resources (centralized authenticator, ingress controller, a number of jobs and daemons that mimic production installations) and the numerous amount of pods, deployments, statefulsets and jobs that developers create in their personal namespaces. I would like to collect logs from important resources and ignore everything else.

**Requirements**:
1) Collect logs to AWS CloudWatch to the `/aws/eks/devel/applicatoin` log group and the `${namespace_name}/${labels.release}/${labels.app}/${container_name}` log stream.
2) Configure the list of namespaces from where the logs need to be collected
3) Be able to add/remove namespaces from log collection with 0 downtime
4) Do not allows developers to change a log tag which I use as a name for the log stream, especially to change the `${namespace_name}/` prefix.
5) Easy to support, ideally I would like to have a single helm release
6) Receive the alert if some container is producing too many log events, say, more than 1k/minute. 
7) number 6) has to be generated based on prometheus metrics

btw, I created a separate issue for 6) and 7) https://github.com/banzaicloud/logging-operator/issues/297

**Solution**

# using your building blocks
I can use the building blocks that logging-operator provides to achieve my goal. To do this I need the following objects: 1 Logging system + 1 ClusterOutput + N Flow, 1 for each namespace that has to be configured for log collection;
However, it will be very problematic to complete the requirements 4) 5) 6) 7), I will need to manage N+1 releases and will need to configure RBAC + admission control hooks, so that nobody can change the <tag> value.

Same issues if I will add 1 logging system for each namespace, except that I can partially complete requirement 6) and 7), because I know for which namespace the prometheus metrics are generated.

# a solution that I used
Generate a custom fluent-bit config, so that fluentbit will filter the namespaces for me. With this solution only 1 helm release is needed. But if fluent-bit must be reconfigured, the daemonset will need to perform rolling update, which means that there will be log duplicates in the target output (cloudwatch). I can avoid this if in a single helm release I will generate N x (custom fluentbit config, Logger) + ClusterFlow + ClusterOutput. But it does not look like the best solution...

# a solution that I see
Add the list of namespaces to the ClusterFlow CRD. In this case only 1 release is needed, also the number of objects in the release is minimal: Logging, ClusterFlow and ClusterOutput CRDs. In case when the list of namespaces must be changed, the fluentd will perform a live config reload.

Do you think it is possible to add the list of namespaces to the spec of a ClusterFlow CRD ? Would you consider this as a general use-case ?

**Comment by pepov** [comment]
I beleive what you need will be possible as soon as we get to make the label router smarter. We are back and forth a little bit on how to implement it, but one of its planned new features is matching on multiple namespaces. (The others are to support excludes and combining multiple selectors with OR statements)

**Comment by tarokkk** [comment]
In the latest release, we provide `namespaces` filtering for ClusterFlow. I hope this solves your problem ;) https://github.com/banzaicloud/logging-operator/releases/tag/3.0.0-rc.1
