### ISSUE TITLE
Wrong LabelSelector in service definition ?

### ISSUE THREAD

**Issue by eddycharly** [banzaicloud/logging-operator#306]
It is not clear to me if it is a bug or not.

What is the purpose of the `app.kubernetes.io/component: query` label in the following service definition ?

https://github.com/banzaicloud/logging-operator/blob/master/charts/logging-operator/templates/service.yaml#L18

I don't see this label in the deployment and therefore the service has no endpoints.

**Comment by pepov** [comment]
yes, this is a bug, thanks for reporting

**Comment by eddycharly** [comment]
thanks for confirming the bug, any plan on fixing it ?
should i open a pull request ?

**Comment by pepov** [comment]
thanks, I would appreciate that!

**Comment by eddycharly** [comment]
ok, is the fix simply removing the label ?

**Comment by pepov** [comment]
I beleive yes

**Comment by eddycharly** [comment]
@pepov i opened a PR
