### ISSUE TITLE
Liveness probe missing

### ISSUE THREAD

**Issue by estahn** [banzaicloud/logging-operator#312]
**Is your feature request related to a problem? Please describe.**
fluentbit reported that it couldn't connect to fluentd. Upon inspecting fluentd it didn't show any issues in particular. We couldn't determine the issue and ended up deleting the pod which resolved the issue. This is obviously not scalable.

**Describe the solution you'd like**
The operator should create fluentd with the required liveliness check. Maybe take some inspiration from https://gist.github.com/heron182/92116abe61a034ffe7410358fcc59186

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ahma** [comment]
@estahn I think you can set liveness check like this:
https://github.com/banzaicloud/logging-operator/blob/master/docs/crds.md#probe
If it's not enough please let me know.

**Comment by estahn** [comment]
@ahma Is there a reason it doesn't have sane defaults? I would expect this comes out of the box.

**Comment by ahma** [comment]
@estahn This is a new feature and that makes an impact on the production environment. This is the reason why we keep it now opt-in.
If you are still missing something about this feature please reopen this issue.

**Comment by pepov** [comment]
Hi, it was missing from the link we referred to above, but there is a boolean flag `livenessDefaultCheck` that enables a liveness check with default values. Please read the docs on what it does:
https://github.com/banzaicloud/logging-operator/blob/master/docs/crds.md#user-content-fluentd-spec

We are also discussing how we could combine this with something more functional, that you mentioned.
