### ISSUE TITLE
Flows with same name in different namespaces cause configcheck error

### ISSUE THREAD

**Issue by pehlert** [banzaicloud/logging-operator#339]
**Describe the bug**:
When creating flows with the same name (in my case `logs-to-loki`) in different namespaces, the configcheck will fail

**Expected behaviour**:
As flows are namespaced resources, it should be allowed to use the same name in different namespaces

**Steps to reproduce the bug**:
- Create a clusteroutput `loki`
- Create two flows with the same name (`logs-to-loki` in this example) in two separate namespaces
- Check configcheck logs

**Additional context**:
Output from configcheck for me:
```
~ » kl -n monitoring logs -f default-logging-fluentd-configcheck-11af17c7
fluentd -c /fluentd/etc/generated.conf --dry-run
2020-01-29 11:36:50 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/generated.conf"
2020-01-29 11:36:50 +0000 [info]: starting fluentd-1.7.4 as dry run mode ruby="2.5.7"
2020-01-29 11:36:50 +0000 [error]: config error file="/fluentd/etc/generated.conf" error_class=Fluent::ConfigError error="Duplicated plugin id `_logs-to-loki_loki_loki`. Check whole configuration and fix it."
```

**Environment details**:
- logging-operator version (e.g. 2.7.0):
- Install method (e.g. helm or static manifests): static manifests

/kind bug

**Comment by pehlert** [comment]
I think an easy way would be to prefix the generated plugin id with the namespace. I'm not super fluent in go, but may be able to come up with a PR if necessary?

**Comment by tarokkk** [comment]
It should be prefixed with FlowName and Namespace as well so this definitely a bug

**Comment by pehlert** [comment]
Brilliant, thanks so much!

**Comment by pbecotte** [comment]
Any workaround ideas while waiting for the release?

**Comment by pepov** [comment]
You could try and go with the `master` image tag as it's built directly from the `master` branch. The only caveat is that some deprecated fields have been removed, so I would recommend checking if you are running on k8s 1.14 or lower because as of k8s 1.15 validation should catch these type of issues automatically.

**Comment by pepov** [comment]
We can also create a 2.7.x branch and backport the fix there and tag a patch version of the image if that would help you better.

**Comment by pbecotte** [comment]
Thinking it through wasn't too bad to namespace the objects temporarily. Thanks for the quick response!
