### ISSUE TITLE
Allow retrieving logs from files and hosts

### ISSUE THREAD

**Issue by SerialVelocity** [banzaicloud/logging-operator#343]
**Is your feature request related to a problem? Please describe.**
1. Pods with log files cannot be output without hardcoding a fluentbit config into the container, copying the current fluentbit secret between namespaces, or deploying another fluentd container
2. Host logs cannot be output without manually setting up the pods with a custom configuration.

**Describe the solution you'd like**

A way to have the two above scenarios dealt with in a nice way and documented. Preferably the sidecars would be added automatically.

**Comment by tarokkk** [comment]
These problems are solved with our logging-extension operator pat of the One Eye product.
https://banzaicloud.com/docs/one-eye/logging-extensions/

As today it supports:
- Host logs
- Event logs
- Sidecar injection (webhook) for Pod file tailing
