### ISSUE TITLE
Add support for fluent-plugin-aws-elasticsearch-service﻿

### ISSUE THREAD

**Issue by jujugrrr** [banzaicloud/logging-operator#361]
**Is your feature request related to a problem? Please describe.**
If you want to use Elasticsearch in AWS you need IAM signing which is supported by the plugin above
**Describe the solution you'd like**
Support for https://github.com/atomita/fluent-plugin-aws-elasticsearch-service﻿
**Describe alternatives you've considered**
Using https://github.com/abutaha/aws-es-proxy or fluentbit https://github.com/fluent/fluent-bit/pull/1852

**Comment by jujugrrr** [comment]
Closing as it seems it's not maintained

**Comment by jujugrrr** [comment]
Oops actually it is

**Comment by ahma** [comment]
https://github.com/banzaicloud/logging-operator/pull/536
