### ISSUE TITLE
Add support web_identity_credentials for eks 

### ISSUE THREAD

**Issue by eric4545** [banzaicloud/logging-operator#362]
This checking limited to use of IRSA, request adding additonal scope for [web_identity_credentials](https://github.com/fluent/fluent-plugin-s3/blob/50e4dc930ac8a5e5434382ad1365c58b9357221c/README.md#web_identity_credentials)

https://github.com/banzaicloud/logging-operator/blob/740282bfd1184d36cd76986aef3f901bb6cfe3fb/pkg/sdk/model/output/s3.go#L264

But also can remove this checking so that aws client will use default credential to assume role that set in the service account

https://github.com/fluent/fluent-plugin-s3/blob/50e4dc930ac8a5e5434382ad1365c58b9357221c/lib/fluent/plugin/in_s3.rb#L248

**Comment by tarokkk** [comment]
Removing this checking seems reasonable, maybe a warning message that it will fallback to some unconfigured defaults
