### ISSUE TITLE
Helm install steps incorrect 

### ISSUE THREAD

**Issue by himansri** [banzaicloud/logging-operator#370]
steps listed here for helm based install of the operator are incorrect https://github.com/banzaicloud/logging-operator/blob/master/docs/deploy/README.md#Deploy-logging-operator-with-Helm.

1) first issue: the command for Helm 3 lists --name logging , which results in error.  "Error: unknown flag: --name"
2)  once above is rectified then it fails with unknown namespace error 'logging' , as the previous steps do not specify creating the namespace.

Minor issues,  so happy to fix existing documentation, if needed

**Comment by ahma** [comment]
@himansri Thanks for the report. we'll fix that asap.
