### ISSUE TITLE
Add plugins to image

### ISSUE THREAD

**Issue by estahn** [banzaicloud/logging-operator#42]
- fluent-plugin-record-reformer
- fluent-plugin-sumologic_output

**Comment by wwojcik** [comment]
https://github.com/banzaicloud/docker-fluentd/pull/7

**Comment by tarokkk** [comment]
Adding plugins to the fluentd requires that the operator is able to use it. Sumologic is already in and supported I'll open a new issue to add fluent-plugin-record-reformer support.
