### ISSUE TITLE
Separate Output and ClusterOutput references for more clarity

### ISSUE THREAD

**Issue by pepov** [banzaicloud/logging-operator#439]
Currently `Output` and `ClusterOutput` objects are referenced ambigously from `Flow` and `ClusterFlow` resources. 

In case of a `Flow` resource both an `Output` and `ClusterOutput` can be referenced the same way. If they have the same name an `Output` will take priority and will shadow the `ClusterOutput`.

In case of a `ClusterFlow` only a `ClusterOutput` can be referenced, but for someone not intimate with this rule is not fully obvious what will happen.

To make this situation clear the reference should be unambigous and `outputRefs` should refer only to namespaced outputs, whereas a new `clusteroutputRefs` field in the `Flow`'s spec should refer to `ClusterOutput` objects only.

**Comment by tarokkk** [comment]
Absolutely agreed! There were several confusions from the users as well, maybe this will clarify the purpose behind those resource types.

**Comment by pepov** [comment]
With https://github.com/banzaicloud/logging-operator/pull/499 now merged we should add namespaced references to clusteroutputs to avoid ambiguity
