### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by bygui86** [banzaicloud/logging-operator#455]
**Is your feature request related to a problem? Please describe.**
My problem is simple: how to properly configure Logging, Flows and Outputs resources.
The documentation lists all available fields, but with default and description columns empty.
This is making almost impossible to properly configure those resources.
For example:
- https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/flow_types/
- https://github.com/banzaicloud/logging-operator/blob/3.1.0/docs/crds/v1beta1/flow_types.md

**Describe the solution you'd like**
Please populate all "default" and "description" columns in all tables in the documentation. The most important ones are [CRDs subpages](https://banzaicloud.com/docs/one-eye/logging-operator/crds/v1beta1/). Then sometimes in [Filters subpages](https://banzaicloud.com/docs/one-eye/logging-operator/plugins/filters/) are missing here and there default values and description values.

**Describe alternatives you've considered**
Without good documentation there is only trial&error method, but this is time consuming and impossible if you don't know available values for fixed lists like "format: gzip | json | text".

**Additional context**
No additional context.

**Comment by tarokkk** [comment]
Those pages are like API reference, there are several pages to help you quickstart https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/ and configure https://banzaicloud.com/docs/one-eye/logging-operator/log-routing/ , the reference is merely for checking parameter names etc... I would love a more detailed documentation PRs are welcome for that as well! Those generated documents built from code comments.

**Comment by bygui86** [comment]
@tarokkk thank you for the answer.

I know what you mean but I don't really agree on that.

Quickstarts are really useful, but they show just some easy hello-world style example, kind 30% of features. It would be great to have something like: an example of multiple flows and outputs at the same time, crossing multiple namespaces as well; an example of exporting logs from microservices written in different languages; an example of exporting logs from applications with very different log formats (kafka, golang, cassandra, traefik, etc.). To produce such examples it would takes lots of tests to me, but this time would be drastically reduced for a current contributor/maintainer.

[elasticsearch output](https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/elasticsearch/) for example is really well documented, but I would not be able to produce such a good and detailed documentation without studying the code deeply, that's why I was asking.

Anyway since last update of the documentation it seems a lot better :)

**Comment by tarokkk** [comment]
As we always try to improve the documentation I'm closing this issue. The more user-friendly version of logging operator is to manage it via One Eye. So I hope those CLI and UI helpers will continue to improve the user experience. https://banzaicloud.com/docs/one-eye/overview/
