### ISSUE TITLE
Add extraVolumeMounts to fluentd statefulset spec

### ISSUE THREAD

**Issue by robbertvdg** [banzaicloud/logging-operator#456]
**Is your feature request related to a problem? Please describe.**
Cannot access S3 variant due to missing SSL certificate in fluentd. The fluentd configuration when creating a Flow does not have an option to include extraVolumeMounts. 

**Describe the solution you'd like**
Add extraVolumeMounts as a configurable option to the fluentd statefulset spec.

**Describe alternatives you've considered**
As an alternative I added a volume mount as kubernetes patch to the existing statefulset, this however is a hotfix instead of an alternative solution. 

**Additional context**

**Comment by tarokkk** [comment]
Can you please elaborate on what kind of SSL certificate you want to install and where? There is a mount option for Secret kind parameters in several plugins.

**Comment by robbertvdg** [comment]
We have Rados on top of Ceph as a self hosted S3 variant. To connect, Fluentd needs a certificate which we provide via a volume mount. I did not see any option in https://banzaicloud.com/docs/one-eye/logging-operator/crds/ to mount this volume for the Fluentd statefulset.

**Comment by tarokkk** [comment]
These kind of integration supported via the plugin output configuration as a secret: https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/secret/. Which output do you use to connect to Rados?
