### ISSUE TITLE
Newer version of fluent-plugin-cloudwatch-logs

### ISSUE THREAD

**Issue by PumpkinSeed** [banzaicloud/logging-operator#457]
**Describe the bug**:
The fluent-plugin-cloudwatch-logs 0.7.6 has a deprecated function call. 
```
#0 Deprecated method: this method is going to be deleted. Use Fluent::MessagePackFactory.msgpack_packer
```
The [issue](https://github.com/fluent-plugins-nursery/fluent-plugin-cloudwatch-logs/issues/171) created on their side, and also fixed. So it would be nice to use a newer version for the build of the fluentd image

**Comment by tarokkk** [comment]
The latest fluentd image will contain the latest available gems

**Comment by ahma** [comment]
Latest version is now supported #487
