### ISSUE TITLE
What to do if the node on which the fluentd runs is down?

### ISSUE THREAD

**Issue by rudolfasd** [banzaicloud/logging-operator#461]
A new pod will not be able to start on another node due to the fact that  PV is not available
How to get around this situation?

**Comment by tarokkk** [comment]
If the Node will come up soon you can simply wait for it and the fluentbits will buffer until. If the Node won't come up you can scale up your fluentd statefulset so another instance can transport your logs. However the logs in the buffer will stay there until a Node comes up with proper zone to be able to remount the PVC.
