### ISSUE TITLE
add ability to specify multiple inputTails

### ISSUE THREAD

**Issue by eljohnson92** [banzaicloud/logging-operator#471]
**Is your feature request related to a problem? Please describe.**
we would like to be able to ingest some system logs along with the container logs. It looks like right now the fluentbit resource only allows for one InputTail path.

**Describe the solution you'd like**
it would be helpful if either multiple InputTail could be given, or a list of paths could be given to InputTail

**Describe alternatives you've considered**
we could also use the customConfigSecret to  accomplish this but it would be nice to have this natively supported, let me know if there is a setting I missed that could be used for this purpose

**Comment by eddycharly** [comment]
Same needs here. Any plan to support that or known workaround ?

**Comment by tarokkk** [comment]
these functionality is supported through One Eye and Logging Extensions https://banzaicloud.com/docs/one-eye/logging-extensions/#kubernetes-host-tailers

**Comment by eddycharly** [comment]
Thanks @tarokkk !
Any chance this can be installed using helm ?

**Comment by eljohnson92** [comment]
thanks, this is exactly what I was looking for! will the logging-operator handle the logging-extension CRD if it is used or is another operated needed specifically for the logging-extension CRD?
