### ISSUE TITLE
pod has unbound immediate PersistentVolumeClaims while trying demo

### ISSUE THREAD

**Issue by nbari** [banzaicloud/logging-operator#476]
Probably not directly a bug, but while giving a try to the docs and following the demo, especially this one: https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/kafka-nginx/

I get from the logs: `pod has unbound immediate PersistentVolumeClaims`

I am trying this with `minikube` using helm

```
helm repo add banzaicloud-stable https://kubernetes-charts.banzaicloud.com
helm update
helm install --namespace logging logging banzaicloud-stable/logging-operator --set createCustomResource=false
helm install --namespace logging logging-demo banzaicloud-stable/logging-demo --set kafka.enabled=True
```

But I am stuck with this error (kubectl -n logging describe pod logging-demo-fluentd-0):

```
Events:
 Type Reason Age From Message
 ---- ------ ---- ---- -------
 Warning FailedScheduling 68s (x24 over 29m) default-scheduler running "VolumeBinding" filter plugin for pod "logging-demo-fluentd-0": pod has unbound immediate PersistentVolumeClaims
```

Any idea about how to fix this?

Thanks in advance.

**Comment by javdet** [comment]
Hello, i have same problem

**Comment by ahma** [comment]
Hi, this is a minikube releadet issue https://github.com/kubernetes/minikube/issues/3869 please use older kuberenetes version `minikube config set kubernetes-version 1.17.0`
