### ISSUE TITLE
Garbage collection for fluentd-configcheck secrets

### ISSUE THREAD

**Issue by estahn** [banzaicloud/logging-operator#483]
**Is your feature request related to a problem? Please describe.**

Our Kubernetes dashboard OOM'ed and after further investigation we think this is most likely related to the number of secrets present. The dashboard probably doesn't paginate, which is a different issue.

The logging operator creates secrets called `*-fluentd-configcheck-*`. These secrets accumulate over time.

**Describe the solution you'd like**
Garbage collect artifacts generated by the logging operator.

**Comment by tarokkk** [comment]
Only the last successful config check should remain available. So I think this is a bug

**Comment by ahma** [comment]
This issue should be fixed with the latest operator version
