### ISSUE TITLE
Use helm v2 crd-install hook to manage CRDs without parameters

### ISSUE THREAD

**Issue by eddycharly** [banzaicloud/logging-operator#485]
Building helm charts compatible with helm v2 and v3 can be tricky.

The `createCustomResource` can be replaced by `crd-install` hook for helm v2 (and the crds folder for v3), see https://github.com/helm/helm/issues/8150.

I can open a PR for this if you're interested.

**Comment by pepov** [comment]
Thanks, but we want to avoid crd-install hooks because there are various issues that make it hard to use properly.
