### ISSUE TITLE
Filter by tag in flow or output ?

### ISSUE THREAD

**Issue by eddycharly** [banzaicloud/logging-operator#495]
Is this possible to match events by tag in a Flow ?

From what I see the match is always **.

Thanks

**Comment by tarokkk** [comment]
It is not. The idea behind it, that the logging operator doesn't use tags for routing. You can use tags in outputs for placeholders etc (with tag_normaliser). It would be extremely difficult to predict logs' direction if we allow routing logs based on that.

**Comment by eddycharly** [comment]
In the end i used a custom secret for fluent-bit because i needed to collect logs from files on the host (i am not using one-eye so i can't use logging-extensions).
I simply added a field there and used that in a grep filter.
Thanks !
