### ISSUE TITLE
Fluentbit cannot connect to fluentd if release tag is set for fluentd in the chart

### ISSUE THREAD

**Issue by baluchicken** [banzaicloud/logging-operator#50]
This commit introduced the error: https://github.com/banzaicloud/logging-operator/commit/4e8912b34e28184dafb271550aac96abc1f5392b

**Comment by baluchicken** [comment]
Fluentd initConfig function set the name for fluentd service if the release tag is set, but this setting is missing from fluent bits config. It looks for fluentd.<namespace>.svc

**Comment by tarokkk** [comment]
I hotfixed (in 6da215741b084a21378c1a97c378a855edbf02c6) to create the service as `fluentd` until we properly refactor naming. I'll keep this issue opened until then.

**Comment by tarokkk** [comment]
This issue is solved in v2
