### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by 2020testuser** [banzaicloud/logging-operator#502]
**Is your feature request related to a problem? Please describe.**
Does banzai Cloud (Logging Operator) support Splunk HEC (HTTP Event Collector). I didn't see the Splunk HEC in the architecture diagram in the BanzaiCloud site. If supported, are there any documentation/samples on its use? Thanks! 

**Describe the solution you'd like**
If Splunk HEC is not supported by Banzai Cloud Logging Operator, it would be good if this can be added to feature request list .

**Describe alternatives you've considered**
None for now as Splunk is used widely in my org.

Thanks!

**Comment by 2020testuser** [comment]
Could anyone please provide some details if you have any information? Thanks!

**Comment by ahma** [comment]
Hi @2020testuser, you can find the docs here -> https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/splunk_hec/

**Comment by 2020testuser** [comment]
@ahma - Thanks Much! Sorry missed it.
