### ISSUE TITLE
Need "Worker N" support to use "Workers"

### ISSUE THREAD

**Issue by pbecotte** [banzaicloud/logging-operator#513]
**Is your feature request related to a problem? Please describe.**
Version 3.3 allowed "workers" in the fluentd spec, which I was excited to use. Unfortunately, the tag_normaliser plugin that I use is not supported. I see that the "Worker N" feature that the fluentd docs recommend to work around this type of issue is not supported.

**Describe the solution you'd like**
The option to wrap flow steps in a worker block. I haven't used fluentd enough outside the operator to know if this actually makes sense- can you have the input in a worker block and then route to a plugin running in a different worker? Just figured it may be useful to file an issue and see your thoughts.

**Describe alternatives you've considered**
For my specific problem, I am going to see if there is another set of plugins I can use to achieve the same thing.

**Comment by ahma** [comment]
I think this is what you looking for https://github.com/banzaicloud/logging-operator/pull/504.

**Comment by pbecotte** [comment]
No, not quite. That lets you declare "workers" - but does not allow you to specify different config for them. If you check https://docs.fluentd.org/deployment/multi-process-workers you'll see that there is a "workers" param in the system directive (which was added) but there is also a "<worker>" directive which wasn't. That lets you specify a specific worker for a filter to run in for ones that dont support multi processing.

I wound up solving my problem by just not using any plugins that required that kind of configuration, but it would be an interesting option to have available.
