### ISSUE TITLE
Splunk HEC Integration

### ISSUE THREAD

**Issue by 2020testuser** [banzaicloud/logging-operator#524]
Could anyone please help me. I'm trying to use Splunk HEC in my Logging Operator in Kubernetes.
Below are my flow and splunk logging yamls under "Expected behavior".

**Describe the bug**:
Below errors appear in Kibana dashboard. However, no errors when I apply the yamls using kubectl cmd.
And , in the splunk dashboard, I don't see any log messages for my applications deployed in 'logging' namespace when I perform a search using my index.

**Expected behaviour**:
No errors must appear in the Kibana dashboard and the splunk dashboard must display all the logs when I perform a search for my index.

**Steps to reproduce the bug**:
1. Install Banzai Cloud Logging Operator in Kubernetes.

2. Create splunk logging and splunk flow yaml and deploy the below yamls using kubectl command in the 'logging' namespace.
splunk-logging.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: splunk-output
spec:
  splunkHec: 
    hec_host: https://<my splunk-host>
    hec_port: 443  
    index: app-index
    hec_token:
      valueFrom:
        secretKeyRef:
          name: logging-creds
          key: hec_token 

splunk-flow.yaml
apiVersion: logging.banzaicloud.io/v1beta1
kind: Flow
metadata:
  name: flow-logging
spec:
  outputRefs:
    - splunk-output  
  match:
    - select: {}

3.  Check in kibana dashboard. You would see the below error.
log:
    {"level":"error","ts":1594841666.46851,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"logging","request":"/logging-operator-logging","error":"failed to create model: referenced output not found: splunk-output","errorVerbose":"referenced output not found: splunk-output\ngithub.com/banzaicloud/logging-operator/pkg/resources/model.(*LoggingResources).CreateFlowFromCustomResource\n\t/workspace/pkg/resources/model/system.go:252\ngithub.com/banzaicloud/logging-operator/pkg/resources/model.(*LoggingResources).CreateModel\n\t/workspace/pkg/resources/model/system.go:77\ngithub.com

4. In Splunk dashboard, when you search using the index used in the yaml, you won't get any result.

**Environment details**:
- Kubernetes version ( v1.16.x)
- logging-operator version (3.4)
- Install method (static manifests)

Please let me know if you need any additional information. 
Thanks in advance!!

/kind bug

**Comment by ahma** [comment]
Hey @2020testuser, it looks like there is some problem with your output, could you please check it ? 
`kubectl get -n logging outputs.logging.banzaicloud.io splunk-output -o yaml`

**Comment by 2020testuser** [comment]
@ahma - Sorry for the delay. I don't see any of my application logs in the splunk dashboard.
Could you please clarify on the below?

1. I have an application namespace (with admin access to the app. namespace and not for all other namespaces). If I set Flow in the app. namespace and refer to the ClusterOutput (created by the admin) in my Flow, I get an error.
Does my userid (non-admin) need to have access to ClusterOutput ?

Thanks!

**Comment by 2020testuser** [comment]
@ahma - Below is the output of kubectl get logging-all -o yaml
Let me know if you need any additional info.
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Flow
  metadata:
    creationTimestamp: "2020-08-17T14:50:38Z"
    generation: 1
    name: splunk-flow
    namespace: test-ns
    resourceVersion: "62726718"
    selfLink: /apis/logging.banzaicloud.io/v1beta1/namespaces/test-ns/flows/splunk-flow
    uid: 5f0ddcce-cbe8-4726-8e44-f6ce6
  spec:
    match:
    - select: {}
    outputRefs:
    - splunk-output
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Output
  metadata:
    creationTimestamp: "2020-08-17T14:50:18Z"
    generation: 1
    name: splunk-output
    namespace: test-ns
    resourceVersion: "627268"
    selfLink: /apis/logging.banzaicloud.io/v1beta1/namespaces/test-ns/outputs/splunk-output
    uid: 2127d4e3-c1043ae-8d0
  spec:
    splunkHec:
      hec_host: https://<my-splunk-server>.com
      hec_port: 443
      hec_token:
        valueFrom:
          secretKeyRef:
            key: hec_token
            name: log-creds
      index: test
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by 2020testuser** [comment]
Below is the output of logging-all  command.

kubectl get logging-all -o yaml     

apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Logging
  metadata:
    creationTimestamp: "2020-08-14T11:14:30Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: test
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/name: logging-operator-logging
      app.kubernetes.io/version: 3.4.0
      helm.sh/chart: logging-operator-logging-3.4.0
    name: logging-operator-logging
    resourceVersion: "627772"
    selfLink: /apis/logging.banzaicloud.io/v1beta1/loggings/logging-operator-logging
    uid: 65670f78-0afc-4b5b-851f-6cf0b
  spec:
    controlNamespace: logging
    fluentbit:
      image:
        pullPolicy: IfNotPresent
        repository: mydocker.com/fluent/fluent-bit
        tag: 1.4.4
      inputTail:
        Mem_Buf_Limit: 45MB
      metrics:
        prometheusAnnotations: true
        serviceMonitor: true
      positiondb:
        hostPath:
          path: ""
      security:
        podSecurityPolicyCreate: true
        roleBasedAccessControlCreate: true
      tls:
        enabled: false
        secretName: logging-fluentbit-tls
    fluentd:
      bufferStorageVolume:
        pvc:
          spec:
            accessModes:
            - ReadWriteOnce
            resources:
              requests:
                storage: 300Gi
            storageClassName: storage
      image:
        pullPolicy: IfNotPresent
        repository: mydocker.com/banzaicloud/fluentd
        tag: v1.10.3-alpine-2
      metrics:
        prometheusAnnotations: true
        serviceMonitor: true
      resources:
        limits:
          cpu: 4000m
          memory: 4096Mi
        requests:
          cpu: 1000m
          memory: 512Mi
      security:
        podSecurityContext:
          fsGroup: 101
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 100
        podSecurityPolicyCreate: true
        roleBasedAccessControlCreate: true
      tls:
        enabled: false
        secretName: logging-fluentd-tls
  status:
    configCheckResults:
      f10ac0cc: true
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by tarokkk** [comment]
Please try to create the Output first and then the Flow (that should eliminate the not found exception in the operator). It shouldn't be a problem just restart the operator and the error should be gone. I think there is a problem with your ingestion config try to check the fluentd log for further error: https://banzaicloud.com/docs/one-eye/logging-operator/troubleshooting/#get-fluentd-logs

**Comment by 2020testuser** [comment]
@tarokkk - Thanks! I did that earlier and still no luck. I don't see the errors (referenced output not found)  in the Elastic Search dashboard now. However, I dont see any of logs info. for my index in the Splunk dashboard.

Could you please let me know what else can be done to resolve this issue? Thanks in advance!

**Comment by ahma** [comment]
@2020testuser The fluentd doesn't log into the stdout this could be a reason why you can't find  any line in ES. Please use the `kubectl exec -it logging-demo-fluentd-0 cat /fluentd/log/out` command because of this. Thanks.

**Comment by 2020testuser** [comment]
@ahma - Thanks! I see some error messages. Below is the output of the cmd.
`kubectl exec -it logging-demo-fluentd-0 cat /fluentd/log/out`

Updated output for dummy values for ns, flow, output and chunk. Could you please let me know why the connection reset msg appears? I did test the Splunk connnectivity using the curl command in my terminal and I'm able to connect and get 200 OK msg. Thanks!

`2020-08-18 18:06:04 +0000 [warn]: #0 suppressed same stacktrace
2020-08-18 20:15:21 +0000 [warn]: #0 [flow:ns:splunk-flow:output:ns:splunk-output] failed to flush the buffer. retry_time=15 next_retry_seconds=2020-08-19 00:27:17 +0000 chunk="5ad28e430a4f867748d2594bb0" error_class=SocketError error="Failed to open TCP connection to https:443 (getaddrinfo: Name does not resolve)"
  2020-08-18 20:15:21 +0000 [warn]: #0 suppressed same stacktrace
2020-08-19 00:27:17 +0000 [warn]: #0 [flow:ns:splunk-flow:output:ns:splunk-output] failed to flush the buffer. retry_time=16 next_retry_seconds=2020-08-19 08:29:21 +0000 chunk="5ad28e430a4f86774ac2594bb0" error_class=SocketError error="Failed to open TCP connection to https:443 (getaddrinfo: Name does not resolve)"
  2020-08-19 00:27:17 +0000 [warn]: #0 suppressed same stacktrace
2020-08-19 08:29:21 +0000 [warn]: #0 [flow:ns:splunk-flow:output:ns:splunk-output] failed to flush the buffer. retry_time=17 next_retry_seconds=2020-08-20 00:46:57 +0000 chunk="5ad28e430a4f867748dc2594bb0" error_class=SocketError error="Failed to open TCP connection to https:443 (getaddrinfo: Name does not resolve)"
  2020-08-19 08:29:21 +0000 [warn]: #0 suppressed same stacktrace`

**Comment by 2020testuser** [comment]
@ahma - Could you please check on the above and let me know if I need to update/add anything in my output? Thanks!

**Comment by ahma** [comment]
@2020testuser Could you please send me more details about your output? (splunkcloud/ on-premis, splunk version), I'll try to reproduce this issue. Thanks!

**Comment by 2020testuser** [comment]
@ahma - Thanks!
Please see the details below. Let me know if you need any additional info.
`Splunk version : 7.3.5`
`Using Splunk Enterprise on-prem`

Splunk Output.yaml file:
`apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
  name: splunk-output
  namespace: <myns>
spec:
  splunkHec: 
    hec_host: https://<splunk-server.com>
    hec_port: 443  
    index: <my-index>

    hec_token:
      valueFrom:
        secretKeyRef:
          name: logging-creds
          key: hec_token
`

**Comment by 2020testuser** [comment]
@ahma - Thanks!
@saiinuganti - #553 is the issue in Logging Operator 3.5.0 and my issue is in Logging Operator 3.4. Similar issue in a different version.

Thanks!

**Comment by ahma** [comment]
@2020testuser I made a test with this and work fine for me. I created a short step by step guide you can find here -> https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/splunk/. I hope this will help you.

**Comment by RaSerge** [comment]
@ahma i tried your step by step guide. after applying output CR i receive error in operator logs:

> {"level":"error","ts":1598949021.0968149,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"logging","request":"/default-logging-simple","error":"failed to update status: Operation cannot be fulfilled on loggings.logging.banzaicloud.io \"default-logging-simple\": the object has been modified; please apply your changes to the latest version and try again","errorVerbose":"Operation cannot be fulfilled on loggings.logging.banzaicloud.io \"default-logging-simple\": the object has been modified; please apply your changes to the latest version and try again\nfailed to update status\ngithub.com/banzaicloud/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/workspace/pkg/resources/fluentd/fluentd.go:119\ngithub.com/banzaicloud/logging-operator/controllers.(*LoggingReconciler).Reconcile\n\t/workspace/controllers/logging_controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}

**Comment by ahma** [comment]
@RaSerge Thanks for your feedback! We just released the new operator version [3.6.0](https://github.com/banzaicloud/logging-operator/releases/tag/3.6.0) could you please test it in your env? Thanks!

**Comment by RaSerge** [comment]
@ahma Thanks for your help!
I install new operator version (3.6.0? with corresponding changes in CRD, and flow CR's.
No errors in fluentd logs. No errors in fluentbit logs. But no logs in splunk and in operator logs i catch same error again:

> {"level":"info","ts":1599113876.5100598,"logger":"controllers.Logging","msg":"there are running configcheck pods, need to back off"}

> {"level":"error","ts":1599113878.7800157,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"logging","request":"/cluster-logging","error":"failed to update status: Operation cannot be fulfilled on loggings.logging.banzaicloud.io \"cluster-logging\": the object has been modified; please apply your changes to the latest version and try again","errorVerbose":"Operation cannot be fulfilled on loggings.logging.banzaicloud.io \"cluster-logging\": the object has been modified; please apply your changes to the latest version and try again\nfailed to update status\ngithub.com/banzaicloud/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/workspace/pkg/resources/fluentd/fluentd.go:119\ngithub.com/banzaicloud/logging-operator/controllers.(*LoggingReconciler).Reconcile\n\t/workspace/controllers/logging_controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"}

it seems that this error and problems with splunkHec output not related.

**Comment by RaSerge** [comment]
I found a problem with fluentbit misconfiguration and can confirm that release 3.6.0 fixed problems with splunkHec output.

**Comment by ahma** [comment]
Thank you guys the tests and the report.
