### ISSUE TITLE
Logging Operator 3.4 with Fluentd - 1.11-1 and Fluentbit - 1.4.6-debug

### ISSUE THREAD

**Issue by 2020testuser** [banzaicloud/logging-operator#525]
**Describe the bug**:
I'm using Banzai Cloud Logging Operator 3.4 with Fluentd - 1.11-1 and Fluentbit - 1.4.6-debug.

I get the below error when I try to apply the logging.yaml with fluentd/fluentbit settings. Could you please let me know whether  Fluentd - 1.11-1 and Fluentbit - 1.4.6-debug works with Logging Operator 3.4 ? Thanks in advance.

 **config error file="/fluentd/etc/generated.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'label_router'. Run 'gem search -rd fluent-plugin' to find plugins".**

Note: The same yaml file works with Logging Operator 3.2 and with older versions of Fluentd and FluentBit.

**Expected behaviour**:
Logging Operator 3.4 with Fluentd - 1.11-1 and Fluentbit - 1.4.6-debug must all work when integrated without any errors.

**Steps to reproduce the bug**:
1. Installed Logging Operator using kubectl create commands.

2. Cloned the Logging Operator git repo. and downloaded to my local machine. Customized the values.yaml for fluentd and fluentbit image/tag name. Use helm template --output-dir to generate the /manifest/logging.yaml file into a specific directory.

3. Used kubectl command to apply the logging.yaml in the cluster. 

4. Received the below error when the pod started.
 config error file="/fluentd/etc/generated.conf" error_class=Fluent::ConfigError error="Unknown output plugin 'label_router'. Run 'gem search -rd fluent-plugin' to find plugins".

**Environment details**:
- Kubernetes version -  v1.16.x

- logging-operator version  - 3.4
- Install method - static manifests

/kind bug

**Comment by ahma** [comment]
HI, @2020testuser we just released the new version of logging-operator 3.5.0 (with fluentd 1.11) could you please check with that?

**Comment by 2020testuser** [comment]
@ahma - Will do. Thanks!
