### ISSUE TITLE
add ability to have a flow apply before any other flows

### ISSUE THREAD

**Issue by eljohnson92** [banzaicloud/logging-operator#532]
**Is your feature request related to a problem? Please describe.**
I would like to be able to apply a simple flow(like adding tags) to all log message regardless of which flow it ends up using

**Describe the solution you'd like**
It would be useful if we had a way to add tags and possibly other flow-related logic to all log messages, regardless of which flow it ends up using, for example in a multi-cluster environment adding which cluster the log messages are coming from.

**Describe alternatives you've considered**
currently, this is being done by using custom fluent bit config to apply tags before the message is forwarded to fluentd.

**Comment by tarokkk** [comment]
This is an interesting approach and needs a bit of planning because the architecture simply does not support such a thing.

**Comment by eljohnson92** [comment]
alternatively having a flow that was tied to an output and applied directly before it is sent to an output could achieve the same thing for our use case. I'm not sure if the implementation for that would still require overcoming the same architecture difficulties.

**Comment by pepov** [comment]
I beleive globalFilters introduced in 0.3.9 should solve this:
https://github.com/banzaicloud/logging-operator/pull/650

Feel free to reopen if it's not the case.
