### ISSUE TITLE
Feature Request: ability to override default docker registry

### ISSUE THREAD

**Issue by chiefy** [banzaicloud/logging-operator#54]
Was trying to test this out inside a very locked down VPC on AWS EKS but it can't connect to outside world to get `busybox`, which I notice is hard-coded. It'd be cool to be able to override this and other image URLs in order to customize things etc.

**Comment by matyix** [comment]
Thanks for reporting is - there is an internal discussion to unify (and add support) these for all operators we have built, so stay tuned.

**Comment by matyix** [comment]
@chiefy this was fixed/released - let me know how it works for you.

**Comment by chiefy** [comment]
@matyix thanks so much for the quick turnaround on this - I was setting up to work on it this weekend and then realized: "oh wow, they already did it!"
