### ISSUE TITLE
Feature Request: parity with latest operator-sdk

### ISSUE THREAD

**Issue by chiefy** [banzaicloud/logging-operator#55]
I realize this might not be high priority, but it'd be great to be able to use the latest operator-sdk to test changes "locally" using `operator-sdk up local` but it's not currently possible due to how the project is structured:

```
❯ operator-sdk up local --namespace=default --kubeconfig=XXX
INFO[0000] Running the operator locally.
FATA[0000] failed to determine operator type
```

osdk is looking for `<project_root>/cmd/manager/main.go` to determine the project type

**Comment by matyix** [comment]
We've been sloppy with this as recently we switched to [kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) on other operators we work on. Nevertheless, we will be upgrading this next week, thanks for reporting.

**Comment by chiefy** [comment]
thanks @matyix we've been using the prometheus-operator and absolutely love the pattern. Also want to move to fluent-bit & fluentd so i'd love to help out.

**Comment by matyix** [comment]
Hello @chiefy - just opened the PR fixing this issue. We are testing it internally (might take 1-2 days) but feel free to check out as well - feedbacks are appreciated. Thanks.
