### ISSUE TITLE
Forward Service

### ISSUE THREAD

**Issue by pieterv-icloud-com** [banzaicloud/logging-operator#552]
**Is your feature request related to a problem? Please describe.**
We currently use the deprecated fluentd-elastisearch helm chart to install fluentd:

https://github.com/helm/charts/tree/master/stable/fluentd-elasticsearch

It exposes a forward service on port 24224 which allows logs to be forwarded to Fluentd from serilog and many other logging frameworks:

    forward-input.conf: |
    <source>
      @type forward
      @log_level debug
      port 24224
      bind 0.0.0.0   
    </source>

**Describe the solution you'd like**
Would you consider exposing this service in the logging operatoer?

**Describe alternatives you've considered**

**Additional context**

**Comment by tarokkk** [comment]
I don't really understand what you want to achieve. If you don't print logs to the stdout the fluentbit won't be able to add metadata to the log. You can use the Kubernetes fluentd service on port 24240 however you have to manually inject Kubernetes metadata or the router will drop your log messages.

**Comment by pieterv-icloud-com** [comment]
This type of logging is for applications to send more structured logs. It's not for Kubernetes logs.
