### ISSUE TITLE
Multiple ClusterFlow per Logging ?

### ISSUE THREAD

**Issue by eddycharly** [banzaicloud/logging-operator#557]
Is having a single Logging and several ClusterFlow supported ?

I don’t see any restriction in the docs but it seems like a lot of events are lost.

**Comment by ahma** [comment]
@eddycharly yes the operator is supporting multiple ClusterFlows at the same time, if it needed. Could you please give us more details about this issue? Thanks

**Comment by ahma** [comment]
I'll close this Issue, please reopen if needs more investigation.
