### ISSUE TITLE
Unavailable links

### ISSUE THREAD

**Issue by Asgoret** [banzaicloud/logging-operator#575]
Hi!
I try to deploy logging operator to OKD 3.11 and want to look at manifests, but links from documentations don't work. Can somebody provide the path to new files (e.g. [deployment.yaml](https://raw.githubusercontent.com/banzaicloud/logging-operator/master/docs/deploy/manifests/deployment.yaml))

**Comment by fekete-robert** [comment]
Hi, this file is at https://github.com/banzaicloud/logging-operator-docs/tree/master/docs/deploy/manifests/
Thanks for the report, we'll check the links

**Comment by Asgoret** [comment]
@fekete-robert if it`s will be useful I can provide readme file and manifests for OKD 3.11 after deploying
