### ISSUE TITLE
Issue with non valid configuration

### ISSUE THREAD

**Issue by shinji62** [banzaicloud/logging-operator#578]
Hello,

First thank you for this great operator it help us quite a lot. 
Unfortunately I can’t make this https://github.com/tektoncd/dashboard/blob/master/docs/walkthrough/walkthrough-logs.md#collecting-taskruns-pod-logs example working, the config checker is failing.

I know and understand that this example is not from Banzai cloud but I was wondering if you see any wrong with it. My guess the path for s3 is not valid, but the config check don’t give much information, so please if you have any idea, let me know because I can’t find what is wrong.

ThAnks

**Comment by tarokkk** [comment]
Can you please paster the config checker logs? And the `kubectl get logging-all --all-namespaces` output?

**Comment by ahma** [comment]
Thanks for the report. I tested it, and woks for me now.  If it still doesn't work for you please reopen this .
