### ISSUE TITLE
Error: container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root

### ISSUE THREAD

**Issue by olemarkus** [banzaicloud/logging-operator#586]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:

Since logging-operator 3.5.0 config checks doesn't run when using PodSecurityPolicy.
Receives error on the banzaicloud/fluentd:v1.11.2-alpine-3 container.
"Error: container has runAsNonRoot and image has non-numeric user (fluent), cannot verify user is non-root"

**Expected behaviour**:
Config checks works 

**Steps to reproduce the bug**:
Install logging-operator with PSP enabled.

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.18.6
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): kops
- logging-operator version (e.g. 2.1.1):
- Install method (e.g. helm or static manifests): helm

/kind bug

**Comment by ahma** [comment]
@olemarkus Thanks for the report! could you please with the new 3.7.0 version?

**Comment by olemarkus** [comment]
Thanks. Looks like 3.7.0 fixed the issue by letting config check use the relevant security features.

**Comment by frjaraur** [comment]
I have this issue in Chart version 3.14.2.
