### ISSUE TITLE
Question: after deploying the loki test getting: no patterns matched tag

### ISSUE THREAD

**Issue by PookiPok** [banzaicloud/logging-operator#596]
I follow the https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/loki-nginx/ and deploy it on my cluster
the problem is i can't see nothing in grafana and in the fluentd logs i see the following :
 #0 no patterns matched tag="logging.logging-demo-log-generator-8586b88f74-r6nmq.log-generator"

Any ideas why?
Gil

**Comment by ahma** [comment]
Thanks @PookiPok! We'll fix it asap.
