### ISSUE TITLE
Configuring http input

### ISSUE THREAD

**Issue by alexsn** [banzaicloud/logging-operator#598]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to configure [http input](https://docs.fluentd.org/input/http) type for fluentd

**Describe the solution you'd like**
Should function similar to existing input sources.

**Describe alternatives you've considered**
Running a seperate fluentd with input/http manually configured.

**Comment by pepov** [comment]
What is your use case for this. What logs would you send to fluentd through this input?

**Comment by alexsn** [comment]
No longer relevant for me but the use case was to forward logs coming from js client (i.e client browser code).

**Comment by pepov** [comment]
Our recommended approach would be to add a separate fluentd with http input and an ingress. If you think that is something that should be supported by the logging operator with for example a new custom resource feel free to reopen.
