### ISSUE TITLE
Logging operator reports CrashLoopBackOff when I try the steps from README to install the operator

### ISSUE THREAD

**Issue by mradha25** [banzaicloud/logging-operator#60]
**Describe the bug**

$ kubectl get pods
NAME                                READY   STATUS             RESTARTS   AGE
logging-operator-795f4f66d4-pr4tb   0/1     CrashLoopBackOff   5          5m33s

kubectl logs logging-operator-795f4f66d4-pr4tb
/usr/local/go/src/runtime/asm_amd64.s:1333
panic: assignment to entry in nil map [recovered]
	panic: assignment to entry in nil map
{"level":"info","ts":1551810833.3330257,"logger":"controller_plugin","msg":"Reconciling Plugin","Request.Namespace":"default","Request.Name":"nginx-logging"}
time="2019-03-05T18:33:53Z" level=info msg="Applying filter"
E0305 18:33:53.434889       1 runtime.go:69] Observed a panic: "assignment to entry in nil map" (assignment to entry in nil map)

**To Reproduce**
Follow the exact steps of readme for logging operator.

**Expected behavior**
Operator pod
Fluentbit and Fluentd daemon sets should have been created
kubectl get pods should have returned all the created resources.

**Screenshots**

**Additional context**

**Comment by baluchicken** [comment]
@mradha25 thanks for reporting this issue, sorry we just updated the README.

**Comment by mradha25** [comment]
Hi, is the issue just with the readme file? I had tried by correcting those glithces.
