### ISSUE TITLE
Add volume mount for certifications on the fluentd container

### ISSUE THREAD

**Issue by nickgerace** [banzaicloud/logging-operator#608]
**Is your feature request related to a problem? Please describe.**
The related problem is that we need a way for ```logging-operator``` users to mount a volume with certificates for some outputs.

Some outputs [require certifications](https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/splunk_hec/) to be on the ```fluentd``` disk, so it would be great to be able to pass them through on the ```logging-operator``` helm chart.

**Describe the solution you'd like**
Adding the volume mount option to the ```logging-operator``` helm chart would be best from a UX perspective.
Perhaps, the mount configuration could be stored, then the operator could apply the configuration to the ```fluentd``` container.
Potentially, users could mount a secret to inject certifications. 

**Describe alternatives you've considered**
I would be happy to learn of an alternative in the interim, but am unaware of one. 

**Additional context**
n/a

**Comment by pepov** [comment]
@nickgerace this is already possible without static helm chart configuration, see:
https://banzaicloud.com/docs/one-eye/logging-operator/plugins/outputs/secret/#define-secret-mount

However it's only available for `Secret` type fields, which may not every plugin conforms to right now.

**Comment by tarokkk** [comment]
It's actually a bug that `ca_file` and `ca_path` is not Secret type in the plugin. We will fix this.

**Comment by nickgerace** [comment]
Thank you all! :)
I appreciate the breakdown and fix.
