### ISSUE TITLE
Some misconfiguration in example chart

### ISSUE THREAD

**Issue by bazzilio** [banzaicloud/logging-operator#618]
> Bugs should be filed for issues encountered whilst operating logging-operator.
> You should first attempt to resolve your issues through the community support
> channels, e.g. Slack, in order to rule out individual configuration errors. [#logging-operator](https://slack.banzaicloud.io/)
> Please provide as much detail as possible.

**Describe the bug**:
When I try to use config from example https://github.com/banzaicloud/logging-operator/blob/master/charts/logging-operator-logging/values.yaml#L56

I got error
` helm upgrade --install  banzai-logging-flow .
Release "banzai-logging-flow" does not exist. Installing it now.
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ClusterOutput.spec.kafka): missing required field "format" in io.banzaicloud.logging.v1beta1.ClusterOutput.spec.kafka`

**Expected behaviour**:
A concise description of what you expected to happen.
No error.

**Steps to reproduce the bug**:
Steps to reproduce the bug should be clear and easily reproducible to help people
gain an understanding of the problem.

- Uncomment lines https://github.com/banzaicloud/logging-operator/blob/3e1f3543e7ad475b65f17ba105185783e22dbb82/charts/logging-operator-logging/values.yaml#L56-L67
- Install helm chart 
- Got error

**Additional context**:

I will try to send you a bit later PR on this issue.

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- logging-operator version (e.g. 2.1.1):
- Install method (e.g. helm or static manifests):
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by ahma** [comment]
Thanks @bazzilio! We'll fix it asap.
