### ISSUE TITLE
helm: charts version 3.7.3 not available in kubernetes-charts.banzaicloud.com

### ISSUE THREAD

**Issue by sdurrheimer** [banzaicloud/logging-operator#622]
**Describe the bug**:
Version 3.7.3 has been cut but is not available in your helm chart repository.

```
chart "logging-operator" version "3.7.3" not found in https://kubernetes-charts.banzaicloud.com repository
```

**Expected behaviour**:
Being able to deploy the logging-operator version 3.7.3.

**Steps to reproduce the bug**:
- Deploy logging-operator helm chart version 3.7.3 using `kubernetes-charts.banzaicloud.com` repository.

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- logging-operator version (e.g. 2.1.1): 3.7.3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by ahma** [comment]
Fixed, thanks @sdurrheimer.
