### ISSUE TITLE
Add syslog output

### ISSUE THREAD

**Issue by nickgerace** [banzaicloud/logging-operator#623]
**Is your feature request related to a problem? Please describe.**
Syslog is currently not a [supported output](https://github.com/banzaicloud/logging-operator/tree/master/pkg/sdk/model/output).

**Describe the solution you'd like**
Having an official syslog ([RFC5424](https://tools.ietf.org/html/rfc5424)) output in the `logging-operator` would be hugely beneficial. Perhaps, `fluentd` would need to process the logs and output them in syslog format. I believe the workarounds could create inconsistency relative to using the other outputs.

**Describe alternatives you've considered**
I can use workarounds, such as [plugins](https://www.fluentd.org/plugins/all) and [syslog forwarders](https://github.com/pivotal-cf/fluent-bit-out-syslog), but am looking for an output included with the `logging-operator`.

**Additional context**

References:
- https://github.com/pivotal-cf/fluent-bit-out-syslog
- https://tools.ietf.org/html/rfc5424
- https://docs.fluentbit.io/manual/pipeline/outputs/syslog
- https://www.fluentd.org/plugins/all
- https://github.com/banzaicloud/logging-operator/tree/master/pkg/sdk/model/output

**Comment by ahma** [comment]
Hi @nickgerace I hope this will help you.

**Comment by nickgerace** [comment]
Thank you @ahma! I really appreciate the quick response and change here. I'll let you know once I get a chance to try it out.

**Comment by nickgerace** [comment]
Hi @ahma - We realized that syslog is not in the outputs file. Is this intended? https://github.com/rancher/dashboard/issues/1191#issuecomment-739066728

**Comment by ahma** [comment]
Hi @nickgerace you are right the crd update is missing. Please check it again. Thanks for the mention.

**Comment by nickgerace** [comment]
No problem! Thank you for the rapid fix :)

**Comment by nickgerace** [comment]
This works excellently now. Thank you @ahma.

**Comment by ahma** [comment]
@nickgerace Glad to hear that.
