### ISSUE TITLE
[charts] logging-operator 3.8.1 released but not available

### ISSUE THREAD

**Issue by sdurrheimer** [banzaicloud/logging-operator#649]
**Describe the bug**:

The logging-operator chart has been [bumped to version 3.8.1](https://github.com/banzaicloud/logging-operator/blob/master/charts/logging-operator/Chart.yaml), but the chart is not available in the repository:
```
Error: chart "logging-operator" version "3.8.1" not found in https://kubernetes-charts.banzaicloud.com repository
```

**Expected behaviour**:
Be able to deploy logging-operator chart version 3.8.1.

/kind bug

**Comment by ahma** [comment]
Hi @sdurrheimer, thanks the issue. I've just released 3.8.2 it's need to solve this issue too.
