### ISSUE TITLE
fluentd logzio plugin issue

### ISSUE THREAD

**Issue by ekhaydarov** [banzaicloud/logging-operator#659]
**Describe the bug**:
``` 
[error]: #0 unexpected error error_class=ArgumentError error="wrong number of arguments (given 2, expected 0)"
[error]: #0 /usr/lib/ruby/gems/2.7.0/gems/net-http-persistent-3.1.0/lib/net/http/persistent.rb:530:in `initialize'
[error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-logzio-0.0.20/lib/fluent/plugin/out_logzio_buffered.rb:47:in `new'
[error]: #0 /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-logzio-0.0.20/lib/fluent/plugin/out_logzio_buffered.rb:47:in `start'
```

issue with gem `net-http-persistence` v3.1.0. when inspecting the image `ghcr.io/banzaicloud/fluentd:v1.11.5-alpine-1` it seems there are two versions of the gem `net-http-persistent (3.1.0, 2.9.4)`. In order to make it work you need to use the 2.9.4 version.

[Here](https://github.com/lostisland/faraday/issues/617#issuecomment-252480645) is a verification that it is the package upgrade issue. I have commented on https://github.com/logzio/fluent-plugin-logzio/issues/35#issuecomment-745574310 but that repo is forgotten. so it would be great if you could make a quick fix here so that we can get logging sorted out if possible?

**Expected behaviour**:
fluentd to start up correctly

**Steps to reproduce the bug**:
do a logging-demo install and try to export to logzio

**Additional context**:

**Environment details**:
- Kubernetes version 1.19.3
- Cloud-provider/provisioner AKS
- logging-operator version (e.g. 2.1.1): 3.8.3
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

/kind bug

**Comment by tarokkk** [comment]
Yeah, but to be honest this is not a Logging Operator issue. This is an issue within a fluentd plugin developed by a 3rd party. You can't expect us to fix fluentd plugins instead of their maintainer. I prefer not to downgrade the HTTP library because of 1 plugin. Typically this would raise other issues of other plugins in endless dependency hell. However, the fix is trivial so we ship a patched version in the latest fluentd container version: `fluentd-v1.11.5-alpine-6`.

**Comment by ekhaydarov** [comment]
Thank you.

We will raise a support ticket with logz from our end to try and get them to fix their plugin.

Much appreciated
