### ISSUE TITLE
Fluent-bit spec does not contain mountPath in the docs

### ISSUE THREAD

**Issue by nickgerace** [banzaicloud/logging-operator#668]
**Describe the bug**:
The `Fluent-bit Spec` does not contain the `mountPath` field, even though [it exists in the logging CRD](https://github.com/banzaicloud/logging-operator/blob/master/pkg/sdk/api/v1beta1/logging_types.go#L377-L379).

**Expected behaviour**:
The `mountPath` field to appear in the [documentation](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluent-bit-spec).

**Steps to reproduce the bug**:
Access the [CRD section of the documentation site](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluent-bit-spec) and navigate to the `Fluent-bit Spec` heading.

**Additional context**:
- https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/#fluent-bit-spec
- https://github.com/banzaicloud/logging-operator/blob/master/pkg/sdk/api/v1beta1/logging_types.go#L377-L379

**Environment details**:
- Kubernetes version (e.g. v1.15.2): n/a
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): n/a
- logging-operator version (e.g. 2.1.1): **3.8.2**
- Install method (e.g. helm or static manifests): **helm**
- Logs from the misbehaving component (and any other relevant logs): n/a
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: n/a

/kind bug

**Comment by pepov** [comment]
there's an outdated part of the docs that is not automatically generated, we will look into it

**Comment by nickgerace** [comment]
Thank you! @pepov

**Comment by ahma** [comment]
Now [looks](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/crds/v1beta1/fluentbit_types/) fine thanks for the report!
