### ISSUE TITLE
[es output] improve support for template_file

### ISSUE THREAD

**Issue by eddycharly** [banzaicloud/logging-operator#671]
From what i understand, when using template_file in the es output, the file has to be mounted beforehand in the fluentd container.

What would be the correct way to do it ?
Wouldn't it be possible to put the template inline in the output spec and have the operator generate a secret that is mounted automatically in the fluentd pod ?

**Comment by eddycharly** [comment]
Any recommendations please ?

**Comment by eddycharly** [comment]
Thanks @pepov !
Going to try this right now.

**Comment by eddycharly** [comment]
Worked like a charm ❤️ 
I guess the same mecanism is supported for ilm ?

Thank you very much !

**Comment by pepov** [comment]
It depends on which field are you thinking of, but I'm afraid no:
https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/elasticsearch/

**Comment by eddycharly** [comment]
I was thinking about `ilm_policy` field, looks like it is supported.
Not the same mecanism as for index templates but as long as there's a way to do it it's fine.
