### ISSUE TITLE
[Feature Request] Add ServiceMonitor to scrape bank-vaults metrics

### ISSUE THREAD

**Issue by sdurrheimer** [banzaicloud/logging-operator#675]
**Is your feature request related to a problem? Please describe.**
The `bank-vaults` container is capable of exporting useful initialized, sealed, and leader metrics, but when using the `prometheus-operator` setup with ServiceMonitors, those metrics are not scraped.

**Describe the solution you'd like**
Add a ServiceMonitor to scrape `bank-vaults` metrics.

**Describe alternatives you've considered**
The ServieMonitor could be added manually but I think the operator should take care of that.

**Additional context**
[Slack discussion](https://community-banzaicloud.slack.com/archives/CFJJW9L94/p1608212083427200)

**Comment by sdurrheimer** [comment]
@bonifaido I'm sorry, I opened the issue on the wrong repository, are you able to move it or should I close and open a new one there?

**Comment by bonifaido** [comment]
Please do.

**Comment by sdurrheimer** [comment]
@bonifaido Here you go https://github.com/banzaicloud/bank-vaults/issues/1238
