### ISSUE TITLE
PSP regression

### ISSUE THREAD

**Issue by yurrriq** [banzaicloud/logging-operator#684]
**Describe the bug**:

#652 introduced a breaking change on some clusters.

**Expected behaviour**:

Successful deployment of the Helm chart.

**Steps to reproduce the bug**:

```bash
helm upgrade --install logging-operator banzaicloud-stable/logging-operator --version 3.9.0
```

**Additional context**:

We, for example, are using k8s 1.18.15 with this AMI: `099720109477/ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20210119.1` Another user reported an issue on 1.20.2 as well (ref: https://github.com/banzaicloud/logging-operator/pull/652#issuecomment-781419351)

**Environment details**:
- Kubernetes version (e.g. v1.15.2): v1.18.15 (and v1.20.2)
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): kOps on AWS
- logging-operator version (e.g. 2.1.1): chart version 3.9.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
```
Error: UPGRADE FAILED: cannot patch "psp.logging-operator" with kind PodSecurityPolicy: PodSecurityPolicy.extensions "psp.logging-operator" is invalid: metadata.annotations[seccomp.security.alpha.kubernetes.io/defaultProfileName]: Invalid value: "docker/default,runtime/default": must be a valid seccomp profile
```
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data: n/a

/kind bug

**Comment by yurrriq** [comment]
@rossmmurray, perhaps you can briefly mention your k8s 1.20 setup.

**Comment by pepov** [comment]
wouldn't it already be safe to simply leave `docker/default` off since it's marked as deprecated since 1.11 https://kubernetes.io/docs/concepts/policy/pod-security-policy/#seccomp

@yurrriq @velothump can you give it a try?

**Comment by szemmouri** [comment]
how did  you  managed  to  fix  this  issue? i'm having the  same  issue on k8s  1.19

**Comment by yurrriq** [comment]
> can you give it a try?

The following works fine for me.

```yaml
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: docker/default,runtime/default
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
```

The trouble is that #652 sets the default profile name to `docker/default,runtime/default`, which is invalid.
