### ISSUE TITLE
Provide possibility to use Elasticsearch Data Stream

### ISSUE THREAD

**Issue by schaenzer** [banzaicloud/logging-operator#697]
**Is your feature request related to a problem? Please describe.**
Elasticsearch has introduced Data stream in version 7.9 [1], which provides a simple way to utilize ILM on time series data. Data streams can unfortunately not be used in the current release because on a data stream the methods to add documents to an index are limited. [2]

**Describe the solution you'd like**
The plugin fluent-plugin-elasticsearch supports data streams from version 5. [3] Therefore the plugin should be updated to the current version and the corresponding output type should be made usable.

**Describe alternatives you've considered**
An alternative would be to utilise `write_operation: create`, however this requires that the key `_id` must be set or generated. For the generation the plugin fluent-plugin-elasticsearch provides in the current used version a filter type. This filter cannot be used in the current release of logging-operator. As an alternative to the proposed solution, this filter could be made available to make the data stream usable

**Additional context**
[1] https://www.elastic.co/guide/en/elasticsearch/reference/7.9/release-highlights.html#_data_streams
[2] https://www.elastic.co/guide/en/elasticsearch/reference/7.11/use-a-data-stream.html#add-documents-to-a-data-stream
[3] https://github.com/uken/fluent-plugin-elasticsearch/tree/v5.0.0#configuration---elasticsearch-output-data-stream
[4] https://github.com/uken/fluent-plugin-elasticsearch/tree/v4.3.3#generate-hash-id

**Comment by eljohnson92** [comment]
I am also interested in shipping logs to a data stream, it would be great if the plugin could be updated.

**Comment by ahma** [comment]
I've now a little dependency problem in our fluentd dockerfile. If it is solved we can deal with this. 
https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/pull/70

**Comment by dzikismigol** [comment]
@ahma do you know when could this be released?

**Comment by mikekuzak** [comment]
Is there anywhere an example how to configure this ? Thanks
