### ISSUE TITLE
Default Buffer_Size for the fluent-bit Kubernetes filter can cause invalid/missing records

### ISSUE THREAD

**Issue by pepov** [banzaicloud/logging-operator#708]
In case the buffer size is not large enough and some API responses doesn't fit into a single buffer, invalid log records will be produced which then won't be routed properly in fluentd.

We need to investigate whether we can make this more error-prone, but at least could increase the default buffer size so that the increased API server responses (supposedly due to the new managedFields) would fit in most cases.

**Comment by ahma** [comment]
https://github.com/banzaicloud/logging-operator/pull/719
