### ISSUE TITLE
fluentd kafka max_send_limit_bytes

### ISSUE THREAD

**Issue by true64gurus** [banzaicloud/logging-operator#714]
I am getting error on fluentd **Kafka::MessageSizeTooLarge"** , I can't seem to find where to set "max_send_limit_bytes" on kafka to less than 1M (kafka default)

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.19.9
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): rancher 2.5.7
- logging-operator version (e.g. 2.1.1): 3.94 , tried 3.9.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs): fluentd
-

/kind bug

**Comment by true64gurus** [comment]
Hi @ahma 

I tried to remove/reinstall logging-operator 3.9.4 , but still it doesn't download updated CRD yamls.

Is there any manual steps I need to do ?

Thanks

**Comment by pepov** [comment]
It depends on how you installed it. Helm doesn't upgrade crds for you, so you have to do that for yourself.

**Comment by ahma** [comment]
This PR isn't released yet. We waiting some other fixies, but we l'll make a new releasa soon. Thanks for your patience!

**Comment by heojay** [comment]
Hi, @ahma
It looks like `max_send_limit_bytes` param mentioned in this issue is not added. Is there any reason?

> max_send_limit_bytes - default: nil - Max byte size to send message to avoid MessageSizeTooLarge. For example, if you set 1000000(message.max.bytes in kafka), Message more than 1000000 byes will be dropped.

Ref. https://github.com/fluent/fluent-plugin-kafka#buffered-output-plugin
