### ISSUE TITLE
Operator does not check if nodeAgent(s) are removed when reconciling a CR of the same name

### ISSUE THREAD

**Issue by mboumsahi** [banzaicloud/logging-operator#728]
When upgrading from 3.9.2 to 3.9.4 chart with Linux nodeAgent(s) installed,  i got the following error

Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Logging.spec): unknown field "nodeAgents" in io.banzaicloud.logging.v1beta1.Logging.spec

Environment details:

Kubernetes version v1.18.10
logging-operator version installed 3.9.2 upgrade to 3.9.4
Install method : helm

**Comment by pepov** [comment]
you have to upgrade the CRDs manually, helm won't do it for you anymore
