### ISSUE TITLE
How to link cert manager with logging operator (without oneeye) 

### ISSUE THREAD

**Issue by karthik012** [banzaicloud/logging-operator#753]
https://banzaicloud.com/docs/one-eye/configure-logging-infrastructure/tls/

This link says how to use certmanger to one-eye to cert manger .

1 . How this could be achieved in the open source version of integration of the logging operator with the cert manager ?

2. If we decide to disable TLS and use Service mesh instead , is there a option in the logging operator ? ( not seen in the Doc)

**Comment by pepov** [comment]
Hi

> 1 . How this could be achieved in the open source version of integration of the logging operator with the cert manager ?

You would have to install cert-manager, generate a server certificate for fluentd and a client certificate for fluentbit, and refer the generated secrets as you can see in the example, nothing else.

> 2. If we decide to disable TLS and use Service mesh instead , is there a option in the logging operator ? ( not seen in the Doc)

There is no option for that just yet.

**Comment by pepov** [comment]
And we are going to fix the indentation in the example, because it's now wrong.
