### ISSUE TITLE
Fluentd replica count should be exposed as a configurable parameter in the fluentd cr.

### ISSUE THREAD

**Issue by chandrabhan319** [banzaicloud/logging-operator#79]
**Currently, the replica count for the fluentd is hardcoded as 1 in the deployment.**

It should be exposed in the fluentd cr as a configurable parameter.

`return &appsv1.Deployment{
                ObjectMeta: templates.FluentdObjectMeta(deploymentName, util.MergeLabels(r.Fluentd.Labels, labelSelector), r.Fluentd),
                Spec: appsv1.DeploymentSpec{
                      Replicas: util.IntPointer(1),`

**Comment by pepov** [comment]
@chandrabhan319 can you elaborate more on how the multi instance deployment scenario should work? I beleive if there are more than one replicas behind the same service then we have to give up message ordering guarantees.

**Comment by pepov** [comment]
closing this, please reopen if it's still relevant
