### ISSUE TITLE
Set dnsConfig and dnsPolicy

### ISSUE THREAD

**Issue by RaSerge** [banzaicloud/logging-operator#794]
Hello!
We have a problems with a heavy dns qps load from our logging layer. Is it possibly to set custom dnsConfig and dnsPolicy for logging-operator controlled fluent-bit daemonset and fluentd statefulset? Or configure dns options (like a caching) for fluent-bit app?
![image](https://user-images.githubusercontent.com/37798887/126738725-8e96758b-9278-47e4-af95-bdc45a5dff30.png)
Thank you!

**Comment by RaSerge** [comment]
I found propertie `nodeAgentFluentbit` in Loggings CRD spec, put dnsConfig and dnsPolicy in corresponding spec, but they don't have positive effect (now Operator try to reconsile Logging resource, throw error and crash)

**Comment by ahma** [comment]
@RaSerge Thanks for the report! I'll look into this
