### ISSUE TITLE
banzaicloud.com/last-applied too long on FluentD configuration secret 

### ISSUE THREAD

**Issue by AmitMatsil** [banzaicloud/logging-operator#837]
Hi all, 

**Describe the bug**:
We recently started to have an issue with one of our clusters. We are using the logging operator with multiple outputs and flows (one per micro-service). Upon adding a new output/flow we are getting `metadata.annotations: Too long: must have at most 262144 characters` error on the secret that contains the FluentD configuration.
This happens because the operator is using the `banzaicloud.com/last-applied` annotation to keep the previous configuration of FluentD, but the max length of the annotations is smaller than the max length of the secret’s data field. 

**Expected behaviour**:
We need to be able to create more resources and increase the FluentD configuration 

**Steps to reproduce the bug**:
Create multiple outputs and flows on the same cluster until you reach the max limit of the annotation. 

**Environment details**:
- Kubernetes version- 1.16.15
- Cloud-provider/provisioner: KOPS
- logging-operator version: 3.3.0
- Install method: Helm
- Logs from the misbehaving component (and any other relevant logs):

> {"level":"error","ts":1629893334.1782067,"logger":"controller-runtime.controller","msg":"Reconciler error","controller":"logging","request":"/logger","error":"failed to reconcile resource: failed to create resource: creating resource failed: Secret \"logger-fluentd-app\" is invalid: metadata.annotations: Too long: must have at most 262144 characters","errorVerbose":"Secret \"logger-fluentd-app\" is invalid: metadata.annotations: Too long: must have at most 262144 characters\ncreating resource failed\ngithub.com/banzaicloud/operator-tools/pkg/reconciler.(*GenericResourceReconciler).CreateIfNotExist\n\t/go/pkg/mod/github.com/banzaicloud/operator-tools@v0.10.1/pkg/reconciler/resource.go:279\ngithub.com/banzaicloud/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/banzaicloud/operator-tools@v0.10.1/pkg/reconciler/resource.go:155\ngithub.com/banzaicloud/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/workspace/pkg/resources/fluentd/fluentd.go:199\ngithub.com/banzaicloud/logging-operator/controllers.(*LoggingReconciler).Reconcile\n\t/workspace/controllers/logging_controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:256\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357\nfailed to create resource\nfailed to reconcile resource","stacktrace":"github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:258\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:232\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.5.0/pkg/internal/controller/controller.go:211\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/pkg/mod/k8s.io/apimachinery@v0.17.4/pkg/util/wait/wait.go:88"} 

/kind bug

**Comment by pepov** [comment]
One possible solution to this is to upgrade the logging operator to at least 3.5.0, where the annotation value is already gzipped.
You might have to delete the secret and let the operator recreate it to use less characters.

**Comment by AmitMatsil** [comment]
Thanks @pepov !
The size of the annotation went down from 250000 charts to 27977 chars. I guess it can still happen on a bigger configuration, but for now, it is solved for us.

**Comment by tarokkk** [comment]
As It resolved for now I'll close this. We can circle back if we have a better solution.
