### ISSUE TITLE
CRDs not upgraded and Fluent::GELFOutput' cannot handle arguments for <buffer ...> section

### ISSUE THREAD

**Issue by luisandresvb** [banzaicloud/logging-operator#840]
We're trying to get the flow directly to Graylog via gelf. I recently saw this feature was included in [#705](https://github.com/banzaicloud/logging-operator/pull/705) and is also documented in the [Outputs ](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/gelf/) section of the docs. Trying to upgrade to the logging-operator 3.4.12 using Helm v3, the created ClusterOutput/Output CRDs don't have the gelf spec. 

_error validating data: ValidationError(ClusterOutput.spec): unknown field "gelf" in io.banzaicloud.logging.v1beta1.ClusterOutput.spec`_ 

After manually deleting the CRDs and reinstalling with Helm, the new CRDs now include gelf spec. Nevertheless, when using the ClusterOutput (or Output) in a ClusterFlow (or Flow), the config-check fail with the following error:

_"config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="this plugin 'Fluent::GELFOutput' cannot handle arguments for <buffer ...> section""_

The Output definition is almost identical to the example in the [docs](https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/gelf/) (attached).

**Additional context**:
Installation command:
helm upgrade --install --wait --create-namespace --namespace logging logging-operator banzaicloud-stable/logging-operator

**Environment details**:
- Kubernetes version: v1.19.4:
- Cloud-provider: Rancher RKE
- logging-operator version: 3.14.2:
- Install method: Helm.
- logs attached.

/kind bug

[configcheck.log](https://github.com/banzaicloud/logging-operator/files/7247735/configcheck.log)
[gelf-clusteroutput.txt](https://github.com/banzaicloud/logging-operator/files/7247739/gelf-clusteroutput.txt)

**Comment by pepov** [comment]
As of the CRD issue: helm won't upgrade the CRDs for you automatically. You have to upgrade them manually or use a tool that does it for you, like ArgoCD.

Another option is to use https://github.com/banzaicloud/crd-updater

**Comment by luisandresvb** [comment]
Thanks Peter! I'm relatively new with Helm and didn't know it.

**Comment by maxaudron** [comment]
I'm running into the same problem, output config is basicly only the following, with or without buffer section doesn't make a difference:
```
spec:
  gelf:
    host: <domain>
    port: 12201
```

and I'm getting the same `'Fluent::GELFOutput' cannot handle arguments for <buffer ...> section` error. I edited the config by hand, removing the buffer section, and put it into the secret, relaunched fluentd and sure enough the config is accepted.

So I think the GELF plugin simply does not support configuring the buffer and this section has to be left out for this. The plugin doesn't set it as a configuration option either: https://github.com/hotschedules/fluent-plugin-gelf-hs/blob/master/lib/fluent/plugin/out_gelf.rb#L15

**Comment by ZleFox** [comment]
it would be good to have an option in the output yaml to not include the default buffer section
