### ISSUE TITLE
Error: unable to decode "": no kind "Fluentbit" is registered for version "logging.banzaicloud.com/v1alpha1"

### ISSUE THREAD

**Issue by Ksreenivas** [banzaicloud/logging-operator#88]
I have tried installing logging-operator in one ec2 machine, followed the steps which are specified in below URL.
https://github.com/banzaicloud/logging-operator#example-logging-operator-with-elasticsearch-operator

**Issue faced**
when I tried to do helm install I have received below error message.
```
helm install --name loggingo banzaicloud-stable/logging-operator --debug 
[debug] Created tunnel using local port: '41795'

[debug] SERVER: "127.0.0.1:41795"

[debug] Original chart version: ""
[debug] Fetched banzaicloud-stable/logging-operator to /home/centos/.helm/cache/archive/logging-operator-0.1.7.tgz

[debug] CHART PATH: /home/centos/.helm/cache/archive/logging-operator-0.1.7.tgz

Error: unable to decode "": no kind "Fluentbit" is registered for version "logging.banzaicloud.com/v1alpha1"
```

```
$ kubectl version --short
Client Version: v1.14.1
Server Version: v1.14.0
```

**Comment by tarokkk** [comment]
This is a Helm issue with installing multiple CRDs (in pre-hook) and CRs afterwards. I'll split this to Helm Chart to 2 separate Helm chart to avoid these race conditions.

**Comment by tarokkk** [comment]
This has been done in v1 as well as v2
