### ISSUE TITLE
Wrong permissions for fluent-plugin-detect-exceptions

### ISSUE THREAD

**Issue by oscisan** [banzaicloud/logging-operator#887]
**Describe the bug**:

Fluentd fails to start with the latest version of logging-operator:

```
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in 'require': cannot load such file -- /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-detect-exceptions-0.0.14/lib/fluent/plugin/out_detect_exceptions (LoadError)
```
There appears to be a difference in permissions on this plugin in the new fluentd image:

```
podman run --rm ghcr.io/banzaicloud/fluentd:v1.13.3-alpine-11 ls -l /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-detect-exceptions-0.0.13/lib/fluent/plugin/
total 24
-rw-r--r--    1 root     root         12491 Oct 24 19:40 exception_detector.rb
-rw-r--r--    1 root     root          4449 Oct 24 19:40 out_detect_exceptions.rb
podman run --rm ghcr.io/banzaicloud/fluentd:v1.13.3-alpine-12 ls -l /usr/lib/ruby/gems/2.7.0/gems/fluent-plugin-detect-exceptions-0.0.14/lib/fluent/plugin/
total 24
-rw-r-----    1 root     root         12916 Nov 26 13:13 exception_detector.rb
-rw-r-----    1 root     root          4614 Nov 26 13:13 out_detect_exceptions.rb
```

Manually setting perms to 644 (like the previous version) makes it work.

**Expected behaviour**:
Fluentd should start and not throw an error message.

**Steps to reproduce the bug**:
Enable detectExceptions in a Flow and fluentd fails to start.

**Additional context**:
None

**Environment details**:
- Kubernetes version (e.g. v1.15.2):
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc):
- logging-operator version (e.g. 2.1.1): 3.16.0
- Install method (e.g. helm or static manifests): 
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:
```apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: x
  namespace: x
spec:
  filters:
    - detectExceptions:
        languages:
        - java
        - python
```

/kind bug

**Comment by kenankule** [comment]
Upstream issue on fluent-plugin-detect-exceptions-0.0.14 is still not fixed : https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exceptions/issues/92
