### ISSUE TITLE
Install logging demo with error "Imagepullbackoff"

### ISSUE THREAD

**Issue by jaggerwang** [banzaicloud/logging-operator#892]
**Describe the bug**:
I'm following this guide [Store Nginx Access Logs in Grafana Loki with Logging operator](https://banzaicloud.com/docs/one-eye/logging-operator/quickstarts/loki-nginx/) to install Loki, Grafana and Logging Demo (Logging Operator is installed by Rancher) on an EKS cluster managed by Rancher. Everything is ok except `logging-demo-log-generator` workload keeps in `updating` status, and the pod shows error "Imagepullbackoff". I tried to change the image version number to `0.3.2` (which exist in docker hub), but it's the same.

![image](https://user-images.githubusercontent.com/1255011/145787516-f1176e10-be38-47e2-a14b-867ce7663f8a.png)

![image](https://user-images.githubusercontent.com/1255011/145786259-4358e004-c609-4921-86fa-8ecd22564a9f.png)

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.21
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): EKS
- logging-operator version (e.g. 2.1.1): 3.12
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):
- Resource definition (possibly in YAML format) that caused the issue, without sensitive data:

**Comment by ahma** [comment]
@jaggerwang thanks for the report I'll look into this

**Comment by ahma** [comment]
@jaggerwang issue is fixed now with the banzaicloud-stable/log-generator chart versrion 0.1.20 please take a look. Thanks tale a look. Thanks
