### ISSUE TITLE
fluentd parse log error

### ISSUE THREAD

**Issue by g-traveller** [banzaicloud/logging-operator#898]
Hi team, 

With log-operator, I got follow warning in Flutend logs, the log from a simple Springboot application
I guess the reason is springboot log is not json format, I don't want to parse this log as json but plain text.

`2021-12-27 09:04:12 +0000 [warn]: #0 send an error event to @ERROR: error_class=Fluent::Plugin::Parser::ParserError error="pattern not matched with data '{\"timestamp\":\"2021-12-27T09:04:11.672Z\",\"level\":\"INFO\",\"thread\":\"http-nio-8080-exec-6\",\"logger\":\"com.porsche.airlineapi.controller.AirlineApiController\",\"message\":\"airline-api stop logging 2021-12-27T09:04:11.672910\",\"context\":\"default\"}\n'" location=nil tag="airline.airlineapi-7f5f9c7df8-c6jbb.airlineapi" time=2021-12-27 09:04:11.749286513 +0000`

Thanks

**Comment by duhow** [comment]
@g-traveller can you share the Flow configuration you're using, and component versions (logging-operator, Fluentd, Fluent-bit) ?

**Comment by ahma** [comment]
HI, @g-traveller we just released the new version of logging-operator 3.17.5 could you please check with that, and if this problem still exist please reopen this issue, Thanks
