### ISSUE TITLE
Output towards S3 Glacier

### ISSUE THREAD

**Issue by richiMarchi** [banzaicloud/logging-operator#899]
**Is your feature request related to a problem? Please describe.**
It would be helpful to directly send logs from Kubernetes to S3 Glacier (never gonna see logs of ingress controllers, but needed to be stored for legal purposes)

**Describe the solution you'd like**
A clusteroutput to directly load logs directly to S3 Glacier, in S3 style

**Describe alternatives you've considered**
Use the S3 standard one, with the bucket lifecycle policy set to 0 days

**Additional context**
If you have suggestion on how to do it, I'd like to listen.

**Comment by ahma** [comment]
I've checked, but I don't find any better solution for this problem than yours.

**Comment by aslafy-z** [comment]
The `storage_class` option is available within the fluentd S3 plugin and within the logging-operator S3 output. See https://github.com/fluent/fluent-plugin-s3/blob/master/docs/output.md#storage_class and  https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/s3/#storage_class-string-optional-output-config-storage_class.
Find the available options (including `GLACIER`) here: https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html#AmazonS3-PutObject-request-header-StorageClass.

**Comment by ahma** [comment]
@aslafy-z Thanks for the details we'll update the documentation.

**Comment by richiMarchi** [comment]
Thank you @aslafy-z, at the end I found the `DEEP_ARCHIVE` value and it worked properly. What I didn't understand it was why the documentation wasn't including all the possible values.
