### ISSUE TITLE
enableRecreateWorkloadOnImmutableFieldChange has no effect on statefulsets

### ISSUE THREAD

**Issue by aslafy-z** [banzaicloud/logging-operator#918]
**Describe the bug**:

`enableRecreateWorkloadOnImmutableFieldChange` has no effect on statefulsets. 

**Expected behaviour**:
Logging operator should re-create the statefulset in order to update immuable fields.

**Steps to reproduce the bug**:

- Create a Logging resource with `enableRecreateWorkloadOnImmutableFieldChange: true`
- Add labels to the FluentdSpec by patching `spec.fluentd.labels` for eg.
- The STS is not recreated and the error arrises.

**Additional context**:

**Environment details**:
- Kubernetes version (e.g. v1.15.2): 1.20.9
- Cloud-provider/provisioner (e.g. AKS, GKE, EKS, PKE etc): RKE
- logging-operator version (e.g. 2.1.1): 3.17.0
- Install method (e.g. helm or static manifests): helm
- Logs from the misbehaving component (and any other relevant logs):

```
failed to reconcile resource: updating resource failed: StatefulSet.apps \"logging-operator-logging-fluentd\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than replicas, template, and updateStrategy are forbidden","errorVerbose":"StatefulSet.apps \"logging-operator-logging-fluentd\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than replicas, template, and updateStrategy are forbidden
updating resource failed
github.com/banzaicloud/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource
        /go/pkg/mod/github.com/banzaicloud/operator-tools@v0.25.4/pkg/reconciler/resource.go:445
github.com/banzaicloud/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile
        /workspace/pkg/resources/fluentd/fluentd.go:227
github.com/banzaicloud/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile
        /workspace/controllers/logging/logging_controller.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:298
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1371
failed to reconcile resource","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214
```

/kind bug

**Solution**:

Upgrade banzaicloud/operator-tools to at least 0.26.0 where the reconciler controller was updated to detect statefulset immuable field change.

see https://github.com/banzaicloud/operator-tools/pull/82, https://github.com/banzaicloud/operator-tools/releases/tag/v0.26.0

**Comment by aslafy-z** [comment]
It looks like this is not fixed. I get the following error on statefulset change:

```
{"level":"error","ts":1646646283.1225023,"logger":"controller.logging","msg":"Reconciler error","reconciler group":"logging.banzaicloud.io","reconciler kind":"Logging","name":"logging-operator-logging","namespace":"","error":"failed to reconcile resource: updating resource failed: StatefulSet.apps \"logging-operator-logging-fluentd\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorVerbose":"StatefulSet.apps \"logging-operator-logging-fluentd\" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden\nupdating resource failed\ngithub.com/banzaicloud/operator-tools/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/banzaicloud/operator-tools@v0.28.2/pkg/reconciler/resource.go:518\ngithub.com/banzaicloud/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/workspace/pkg/resources/fluentd/fluentd.go:227\ngithub.com/banzaicloud/logging-operator/controllers/logging.(*LoggingReconciler).Reconcile\n\t/workspace/controllers/logging/logging_controller.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581\nfailed to reconcile resource","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227"}
```

**Comment by aslafy-z** [comment]
I think one of these two pull-request might do the thing: 
- https://github.com/banzaicloud/logging-operator/pull/941
- https://github.com/banzaicloud/operator-tools/pull/103

Not sure which path you prefer. Let me know so I tidy up the associated PR.

**Comment by houshym** [comment]
I have same error:
Rancher logging operator 

{"level":"error","ts":1646892399.4881766,"logger":"controller-runtime.manager.controller.logging","msg":"Reconciler error","reconciler group":"logging.banzaicloud.io","reconciler kind":" Logging","name":"rancher-logging","namespace":"","error":"failed to reconcile resource: updating resource failed: StatefulSet.apps \"rancher-logging-fluentd\" is invalid: spec: Forbidden  : updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden","errorVerbose":"StatefulSet.apps \"rancher-logging-fluentd\" is invalid: s  pec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', and 'updateStrategy' are forbidden\nupdating resource failed\ngithub.com/banzaicloud/operator-to ols/pkg/reconciler.(*GenericResourceReconciler).ReconcileResource\n\t/go/pkg/mod/github.com/banzaicloud/operator-tools@v0.25.4/pkg/reconciler/resource.go:445\ngithub.com/banzaicloud/logging-operator/pkg/resources/fluentd.(*Reconciler).Reconcile\n\t/workspace/pkg/resources/fluentd/fluentd.go:227\ngithub.com/banzaicloud/logging-operator/controllers.(*LoggingReconciler).Re │
│ concile\n\t/workspace/controllers/logging_controller.go:128\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-r │
│ untime@v0.9.5/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-ru │
│ ntime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v │
│ 0.9.5/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371\nfailed to reconcile resource","stacktrace":"sigs.k8s.io/controller-runtime/ │
│ pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/p │
│ kg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/internal/controller/controller.go:214"}
