### ISSUE TITLE
Support for multi-container pods

### ISSUE THREAD

**Issue by jasonaliyetti** [banzaicloud/logging-operator#96]
**Is your feature request related to a problem? Please describe.**
A common deployment scenario is to use sidecar containers (i.e. Istio) that have varying log formats.  I see no way of parsing my application container's output while providing alternative formatting for something like the istio-proxy container in the same pod.  This is doable via Fluentd, but the operator does not seem to support it. This currently prevents me from adopting the operator.

**Describe the solution you'd like**
It would be nice to be able to define filters/parsing and outputs at the container level.

**Describe alternatives you've considered**
N/A

**Additional context**
This is more of a side note, but one thing I thought of to work around these kinds of issues would be to allow the Plugin resource to define an explicit Fluentd configuration.  That would enable users to leverage the operator's Fluentd config aggregation provided by this plugin more readily.

**Comment by tarokkk** [comment]
Hey @jasonaliyetti . The current version of the operator does not support this kind of log selection. However the next release which will support custom label selectors will be able to distinguish based on container labels. So it will be possible to differentiate containers via these labels.

The additional comment about raw config is a recurring issue as well. We will try to shape the CRD to fit in with that kind of advanced usage as well.

**Comment by jasonaliyetti** [comment]
@tarokkk Thank you.

**Comment by tarokkk** [comment]
The v2 out so it is possible to create any label selector: https://github.com/banzaicloud/logging-operator/tree/v2

**Comment by jroper** [comment]
> However the next release which will support custom label selectors will be able to distinguish based on container labels.

Can you elaborate on this? How are container labels defined? Are these the same as [docker labels](https://docs.docker.com/config/labels-custom-metadata/)? Or is it more like you can add a selector of `container-name: foo` to get logs from containers named foo? Is there any documentation on this or examples of selecting logs by container? The only documentation I can find just talks about Kubernetes pod labels.

**Comment by pepov** [comment]
@jroper sorry, we were really referring to pod labels, however we are also working on adding the container name to the mix, so that you should be able to define flows that select/exclude on the container name as well.

**Comment by naviat** [comment]
Sorry for recalling this request but after 2 years, Do we have any update for label selectors with container labels? @jroper  Do you have any other solution for it?

**Comment by jroper** [comment]
I didn't end up using the logging operator, it was lacking the features I needed, including this one.

**Comment by naviat** [comment]
Good to know this, I think banzai should be more active on this product when it's not up to date with so many plugins.

**Comment by siliconbrain** [comment]
@naviat What do you mean by *container labels*?

Filtering based on container name was added in [3.0.0](https://github.com/banzaicloud/logging-operator/releases/tag/3.0.0) shortly after @pepov's [comment](https://github.com/banzaicloud/logging-operator/issues/96#issuecomment-590791817). It's documented here: https://banzaicloud.com/docs/one-eye/logging-operator/configuration/log-routing/ There is no specific example of using it, but it should be quite easy to infer.

I would also like to note that this is a free, open source project accepting pull requests from "non-banzai" contributors.
