### ISSUE TITLE
Could you please add support of fluent-plugin-opensearch

### ISSUE THREAD

**Issue by AlKapkone** [banzaicloud/logging-operator#971]
Currently, Logging Operator supports only this plugin https://github.com/atomita/fluent-plugin-aws-elasticsearch-service
which is very poor on options (no debug options and without new functionality and commits - latest on 21 Apr 2021).

Could you please add this https://github.com/fluent/fluent-plugin-opensearch plugin as an option to ClusterOutputs Spec?
This plugin has more commits and contributors and a huge number of options (including specific for AWS and debug options). 

Why do you decide to use the "dead" plugin **fluent-plugin-aws-elasticsearch-service** for AWS OpenSearch Service?
Is it possible to add this **fluent-plugin-opensearch**?

**Comment by andrevcf** [comment]
Please, add the fluent-plugin-opensearch plugin! :100:
