### ISSUE TITLE
Please add log_es_400_reason parameter support for fluent-plugin-aws-elasticsearch-service plugin

### ISSUE THREAD

**Issue by AlKapkone** [banzaicloud/logging-operator#980]
I need the `log_level` debug or at least the `log_es_400_reason` parameter. I use the fluent-plugin-aws-elasticsearch-service (2.4.1) plugin, described here - https://banzaicloud.com/docs/one-eye/logging-operator/configuration/plugins/outputs/aws_elasticsearch/

I've created an issue here in the fluent-plugin-aws-elasticsearch-service plugin repo:
Link - https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/81

The collaborator of the fluent-plugin-aws-elasticsearch-service told me that you should add support for this parameter from your side.

Adding log_es_400_reason parameter support is required here:
https://github.com/banzaicloud/logging-operator/blob/c9722ee319584ff75ebda49ef4095b6bf127d7d4/pkg/sdk/model/output/aws_elasticsearch.go
Like as this PR: https://github.com/banzaicloud/logging-operator/pull/858

**Comment by AlKapkone** [comment]
More details here - https://github.com/atomita/fluent-plugin-aws-elasticsearch-service/issues/81

**Comment by ahma** [comment]
As I know we are already supporting this [parameter](https://github.com/banzaicloud/logging-operator/blob/c9722ee319584ff75ebda49ef4095b6bf127d7d4/pkg/sdk/model/output/elasticsearch.go#L213) please check this and if its not working please reopen this issue.  Thanks you.

**Comment by AlKapkone** [comment]
https://github.com/banzaicloud/logging-operator/blob/c9722ee319584ff75ebda49ef4095b6bf127d7d4/pkg/sdk/model/output/aws_elasticsearch.go#L50
Looks like I need this parameter here because I use the AWS ElasticSearch service.

**Comment by AlKapkone** [comment]
@ahma So I still need your help, please.
